ehrbase/ehrbase

- base/src/main/resources/db/migration/V8__folders_support.sql
- service/src/main/java/org/ehrbase/dao/access/jooq/FolderAccess.java
- service/src/test/java/org/ehrbase/dao/access/jooq/FolderAccessTest.java
- service/src/test/java/org/ehrbase/dao/access/jooq/FolderMockDataProvider.java
corrects some bugs and cascade deletions that were present when testing against the real DB. Also standardizes line changes so the FolderAccessTests run in all platforms.
@Reviewer please confirm the latter works in Windows before approval.
> 7 run and check all tests in folder access test.java against the real db

- jooq-pq/pom.xml
- service/src/main/java/org/ehrbase/dao/access/interfaces/I_FolderAccess.java
- service/src/main/java/org/ehrbase/dao/access/jooq/FolderAccess.java
- service/src/test/java/org/ehrbase/dao/access/jooq/FolderAccessTest.java
- service/src/test/java/org/ehrbase/dao/access/jooq/FolderMockDataProvider.java
- Extended Jakes OtherDetailsJsonbBinder to also bew aware of details column for folders
- Replaced usage of PGObectParser by new binded ItemStructure
- Updated Tests for usage of ItemStructure.
@jakesmolka: 
Please give a short feedback if I correctly understand the usage of the binder. I added the regular expression as discussed. I also made them more strict since the regex `.*details.*` would break the generation of "audit_details". If we want to add more ItemStructure columns here, we must add them to the regular expression.
@lmarcoruiz: 
This seems to be the solution for the ItemStructure and also a pattern we can reuse for the SysPeriod columns of all tables.
Can you look over the FolderAccess and FolderAccessTest if the adaptions to the usage of ItemStructure instead of Object and …
> Bugfix for #43 PGObject cannot be cast to ItemStructure

- service/src/test/java/org/ehrbase/dao/access/jooq/FolderAccessTest.java
Added the Ignores for failing tests to FolderAccess Tests not running after ItemStructure Binding
> Deactivated failing FolderAccess tests

- LICENSE.md
- tests/Taskfile.yml
- tests/requirements.txt
- tests/robot/COMPOSITION_TESTS/JSON1/__init__.robot
- tests/robot/COMPOSITION_TESTS/JSON2/B.8.c_alternative_flow_1_delete_non_existent_COMPOSITION.robot
- tests/robot/COMPOSITION_TESTS/JSON2/__init__.robot
- tests/robot/COMPOSITION_TESTS/XML1/__init__.robot
- tests/robot/COMPOSITION_TESTS/XML2/__init__.robot
- tests/robot/COMPOSITION_TESTS/__init__.robot
- tests/robot/KNOWLEDGE_TESTS/C.1.a_validate_valid_OPTs.robot
- tests/robot/KNOWLEDGE_TESTS/C.1.b_validate_invalid_OPTs.robot
- tests/robot/KNOWLEDGE_TESTS/C.2.a_upload_valid_OPTs.robot
- tests/robot/KNOWLEDGE_TESTS/C.2.b_upload_invalid_OPTs.robot
- tests/robot/KNOWLEDGE_TESTS/C.2.c_upload_valid_OPT_twice_with_conflict.robot
- tests/robot/KNOWLEDGE_TESTS/C.3.a_retrieve_single_OPT.robot
- tests/robot/KNOWLEDGE_TESTS/C.3.b_empty_server_OPT_retrieve_fail_test.robot
- tests/robot/KNOWLEDGE_TESTS/C.3.c_retrieve_last_version_of_versioned_OPT.robot
- tests/robot/KNOWLEDGE_TESTS/C.3.d_retrieve_specific_version_of_versioned_OPT.robot
- tests/robot/KNOWLEDGE_TESTS/C.4.a_retrieve_all_loaded_OPTs.robot
- tests/robot/KNOWLEDGE_TESTS/C.4.b_retrieve_all_loaded_OPTs_when_none_is_loaded.robot
- tests/robot/KNOWLEDGE_TESTS/__init__.robot
- tests/robot/_resources/keywords/db_keywords.robot
- tests/robot/_resources/keywords/generic_keywords.robot
- tests/robot/_resources/keywords/template_opt1.4_keywords.robot
- tests/robot/_resources/suite_settings.robot
- created db_keywords resource file with first DB keywords:
- Connect With DB
- Delete All Templates
- Get Information About DB Table
- Count Rows In DB Table
- changed "restart SUT" behaviour to do only one thing: Delete All Templates
- disabled ehrbase server cache during test execution
- added robotframework-databaselibrary and required dependencies
- added license information of new test dependencies
- added new task to Taskfile.yml: start ehrbase server without cache
- adjusted some __init__ files and tests  to work with new "restart SUT" behavior
- updated KNOWLEDGE tests
- removed obsolete SUT restarts to speed up test execution
- replaced restarts with "Delete All Templates" kw
> Adds RF keywords for DB operations - ehrbase/project_management#30

- serialisation/src/main/java/org/ehrbase/ehr/encode/wrappers/json/writer/DvDurationAdapter.java
- serialisation/src/main/java/org/ehrbase/ehr/encode/wrappers/json/writer/translator_db2raw/LinkedTreeMapAdapter.java
Trivial fixes. However, NPEs are a side effect of badly encoded DvDuration values. I have opened a ticket #97 to address this issue.
> fixed NPEs

- service/src/main/java/org/ehrbase/aql/compiler/QueryCompilerPass2.java
- service/src/test/java/org/ehrbase/aql/compiler/AqlExpressionTest.java
duplicated aliases in select are now rejected unless used in a function.
> detect duplicate aliases in aql select

- rest-openehr/src/main/java/org/ehrbase/rest/openehr/response/QueryResponseData.java
- service/src/main/java/org/ehrbase/dao/access/jooq/AqlQueryHandler.java
Fixes several AQL issues as in https://github.com/ehrbase/project_management/issues/65
```
{
"q": "SELECT e/ehr_id/value FROM EHR e",
"name": null,
"columns": [],
"rows": []
}
```
Now, the list of columns is correctly set and in the order defined in the select statement. Further, if null, attribute 'name' is not in the json structure.
> fix empty name, rows but display columns. Preserver order of variables

- CHANGELOG.md
- pom.xml
Update of Dependency done. No breaking change inside Release Notes of Jackson and no issues identified during tests of new version.
Closes ehrbase/project_management#136
> Raise jackson versions to 2.10.2

- serialisation/src/main/java/org/ehrbase/serialisation/CompositionSerializer.java
- test-data/src/main/resources/composition/canonical_xml/diadem.xml
I've added a PR to fix an issue I have seen when saving a composition that contains a provider
* Updating CompositionSerializer to handle the PartyIdentified name field as a string rather than DvText
* Updating diadem.xml to include provider on an evaluation so the RawJsonTest unmarshall test confirms there is no errors deserialising the provider details
> Error when reading a composition that has a provider name set - fix

- tests/README.md
- tests/Taskfile.yml
- tests/robot/DIRECTORY_TESTS/A.4_GET_DIRECTORY/A.4__c._EHR_with_complex_directory_structure_and_item.robot
- tests/robot/_resources/keywords/composition_keywords.robot
- tests/robot/_resources/keywords/directory_keywords.robot
- tests/robot/_resources/keywords/ehr_keywords.robot
- tests/robot/_resources/keywords/generic_keywords.robot
- tests/robot/_resources/suite_settings.robot
- tests/run_local_tests.sh
resolves https://github.com/ehrbase/project_management/issues/117
- added ~Test Environment~ SUT (system under test) configs to suite_settings
- target SUT can now be defined in suite_settings.robot and switching requires only to change `${SUT}` variable, which can be done in suite_settings or from command line
- added a command line option to allow manual control of the ~test environment~ SUT (`-v nodocker`)
- updated resource files:
- composition_keywords
- directory_keywords
- ehr_keywords
- generic_keywords
- fixed typo in a KW in DIRECTORY_TESTS
- updated/fixed my Taskfile.yml
> SUT switch - https://github.com/ehrbase/project_management/issues/117

- service/src/main/java/org/ehrbase/aql/sql/queryImpl/attribute/GenericJsonPath.java
- service/src/main/java/org/ehrbase/aql/sql/queryImpl/attribute/ehr/ehrstatus/EhrStatusOtherDetails.java
- service/src/test/java/org/ehrbase/aql/sql/queryImpl/attribute/GenericJsonPathTest.java
AQL Querying other_details `SELECT  e/ehr_status/other_details` for an EHR defined as follows is now supported
```
{
"_type": "EHR_STATUS",
"archetype_node_id": "openEHR-EHR-EHR_STATUS.generic.v1",
"name": {
"value": "EHR Status"
},
"subject": {
"external_ref": {
"id": {
"_type": "GENERIC_ID",
"value": "ins03",
"scheme": "id_scheme"
},
"namespace": "examples",
"type": "PERSON"
}
},
"other_details": {
"_type": "ITEM_TREE",
"archetype_node_id": "at0001",
"name": {
"value": "Details"
},
"items": [
{
"_type": "ELEMENT",
"name": {
"_type": "DV_TEXT",
"value": "Field 1"
},
"archetype_node_id": "at0111",
"value": {
"_type": "DV_DATE_TIME",
"value": "2014-02-05T12:54:54"
}
},
{
"_type": "ELEMENT",
"name": {
"_type": "DV_TEXT",
"value": "Field 2"
},
"archetype_node_id": "at0222",
"value": { …
```
> AQL support of ehr_status/other_details

- service/src/main/java/org/ehrbase/aql/sql/postprocessing/RawJsonTransform.java
This fixes a NPE whenever a canonical json result is null (e.g. non existent)
Closes: https://github.com/ehrbase/project_management/issues/186
> Deals with an empty result for canonical item structure

- service/src/main/java/org/ehrbase/dao/access/interfaces/I_ConceptAccess.java
- tests/robot/_resources/test_data_sets/valid_templates/minimal/minimal_observation.composition.participations.extdatetimes.ehrbase.json
According to https://specifications.openehr.org/releases/TERM/latest/SupportTerminology.html the correct term for the support terminology is `openehr` and not `openEhr`.
Contributions were only accepted with the `openehr` term while the output always produced `openEhr`.
> use openehr instead of openEhr as terminology_id

- base/src/main/resources/terminology.xml
- test-data/src/main/resources/composition/canonical_json/full_composition.json
- test-data/src/main/resources/composition/canonical_json/rawdb_composition.json
- tests/robot/_resources/test_data_sets/valid_templates/minimal/minimal_observation.composition.participations.extdatetimes.ehrbase.json
This is a partial fix for #114. It changes the term "Event" to lowercase, according to the specification.
Together with #113, this makes ehrBase generate valid representations from the raw JSON stored in the database.
> lowercase event

- service/src/main/java/org/ehrbase/dao/access/jooq/TemplateStoreAccess.java
- service/src/main/java/org/ehrbase/service/TemplateFileStorageService.java
- service/src/main/java/org/ehrbase/service/TemplateServiceImp.java
Added explicit conversion to UTF-8.
- First change
Fixes https://github.com/ehrbase/project_management/issues/112
> added explicit UTF-8 encoding when reading to byte

- service/src/main/antlr4/org/ehrbase/aql/parser/Aql.g4
- service/src/main/java/org/ehrbase/aql/compiler/WhereClauseUtil.java
- service/src/main/java/org/ehrbase/aql/compiler/WhereVisitor.java
- service/src/main/java/org/ehrbase/aql/containment/IdentifierMapper.java
- service/src/main/java/org/ehrbase/aql/definition/FromEhrDefinition.java
- service/src/main/java/org/ehrbase/aql/sql/binding/I_TaggedStringBuilder.java
- service/src/main/java/org/ehrbase/aql/sql/binding/TaggedStringBuilder.java
- service/src/main/java/org/ehrbase/aql/sql/binding/WhereBinder.java
- service/src/main/java/org/ehrbase/aql/sql/binding/WhereJsQueryExpression.java
- service/src/test/java/org/ehrbase/aql/compiler/AqlExpressionTest.java
- service/src/test/java/org/ehrbase/aql/compiler/QueryCompilerPass1Test.java
- service/src/test/java/org/ehrbase/aql/compiler/WhereClauseUtilTest.java
- service/src/test/java/org/ehrbase/aql/compiler/WhereVisitorTest.java
- service/src/test/java/org/ehrbase/aql/sql/QueryProcessorTest.java
- service/src/test/java/org/ehrbase/aql/sql/binding/WhereBinderTest.java
- service/src/test/resources/samples/191_where_parenthesis.aql
- Modified Aql.g4 grammar to enable parenthesis support in WHERE clause
- Refactored WhereBinder since it was not supporting multi-level parenthesis expression
- Added parenthesis and other delimiter balancing validation
- Added more unit test
- Fix unit test (case #12  of QueryProcessorTest was wrongly assuming the IN operator was supported by JsQuery) 
Closes: https://github.com/ehrbase/project_management/issues/191
> support parenthesis in WHERE clause

- serialisation/src/main/java/org/ehrbase/ehr/encode/rawjson/LightRawJsonEncoder.java
- serialisation/src/main/java/org/ehrbase/ehr/encode/wrappers/json/writer/translator_db2raw/EmbeddedValue.java
- serialisation/src/main/java/org/ehrbase/ehr/encode/wrappers/json/writer/translator_db2raw/IterativeItemStructure.java
- serialisation/src/main/java/org/ehrbase/ehr/encode/wrappers/json/writer/translator_db2raw/LinkedTreeMapAdapter.java
- serialisation/src/test/java/org/ehrbase/serialisation/DBEncodeTest.java
- test-data/src/main/resources/composition/canonical_json/rawdb_composition_history.json
- test-data/src/main/resources/composition/canonical_json/rawdb_composition_observation_event.json
- test-data/src/main/resources/composition/canonical_json/rawdb_composition_observation_event_item.json
- test-data/src/main/resources/composition/canonical_json/rawdb_returning_array.json
This is to fix several issues when returning canonical json in AQL:
```
{
"q": "select o/data[at0001]
from EHR e
contains COMPOSITION c
contains OBSERVATION o[openEHR-EHR-OBSERVATION.minimal.v1]
" 
}
```
Was:
```
"rows": [
[
{
"name": {
"value": "Event Series"
},
"events": {
"events": [
{
"name": {
"value": "Cualquier evento"
},
"time": {
"value": "2019-01-28T21:22:19.562Z",
"_type": "DV_DATE_TIME"
},
``` 
The expression
```
"events": {
"events": [
```
is replaced with 
```
"events": [
```
```
{
"q": "select o/data[at0001]/events[at0002]
from EHR e
contains COMPOSITION c
contains OBSERVATION o[openEHR-EHR-OBSERVATION.minimal.v1]
" 
}
```
Was
```
"rows": [
[
{
"items": [
{
"name": {
"value": "Cualquier evento"
},
"time": {
"value": "2019-01-28T21:22:19.562Z",
"_type": "DV_DATE_TIME"
}, …
```
> refactoring and fixes to support correct canonical json representation

- .circleci/config.yml
- CHANGELOG.md
- README.md
- application/Dockerfile
- application/docker-compose.yml
- application/pom.xml
- application/src/main/java/org/ehrbase/application/config/SecurityConfig.java
- application/src/main/java/org/ehrbase/application/config/SecurityYAMLConfig.java
- application/src/main/java/org/ehrbase/application/config/WebMvcConfig.java
- application/src/main/java/org/ehrbase/application/util/StringToEnumConverter.java
- application/src/main/resources/application-cloud.yml
- application/src/main/resources/application-docker.yml
- application/src/main/resources/application-local.yml
- application/src/main/resources/application.yml
- pom.xml
- tests/Taskfile.yml
- tests/robot/EHR_SERVICE_TESTS/B.1_CREATE_EHR/B.1__a)_New_EHR.robot
- tests/robot/_resources/suite_settings.robot
:lock: Basic Auth support from Spring Security and can be set via env
:pencil: Add documentation for Basic Auth configuration and usage via
docker
project_management#114
- Add Configuration for Basic Auth with Spring Security
- Add Docker env variables for Basic auth usage
- Add documentation for EHRbase and Docker image usage
Closes https://github.com/ehrbase/project_management/issues/114
> Basic Auth support

- CHANGELOG.md
- service/src/main/java/org/ehrbase/aql/sql/queryImpl/EntryAttributeMapper.java
- service/src/main/java/org/ehrbase/aql/sql/queryImpl/JsonbEntryQuery.java
fix bad canonical json formatting when querying and observation origin (f.e.```o/data[at0001]/origin`` where `o` is an OBSERVATION.
closes: https://github.com/ehrbase/project_management/issues/225
> fixes origin querying as well as name canonical json representation

- service/src/main/java/org/ehrbase/aql/sql/binding/OrderByBinder.java
- service/src/main/java/org/ehrbase/aql/sql/binding/SuperQuery.java
- service/src/test/java/org/ehrbase/aql/sql/QueryProcessorTest.java
- service/src/test/java/org/ehrbase/aql/sql/binding/OrderByBinderTest.java
Fixes handling of multiple columns in ORDER BY statement
fixes: https://github.com/ehrbase/ehrbase/issues/230
> fix order by identifiers and force double-quoted column ids

- service/src/main/java/org/ehrbase/aql/sql/WhereTemporal.java
- service/src/main/java/org/ehrbase/aql/sql/binding/ExpressionField.java
- service/src/main/java/org/ehrbase/aql/sql/binding/WhereBinder.java
fixed OutOfBound exception for specific aql encoding
This allows using datetime comparison in AQL where clause.
The issue is that whenever using jsquery, comparison is allowed for numerical values only (https://github.com/postgrespro/jsquery). This fix address simple datetime formats a more general solution would be more complex to implement due to the great (!) variety of date encoding... It is therefore recommended and assumed the format of stored datetime (partial in particular is known in advance). That said, comparisons such as:
```
m/data[at0001]/items[at0004]/value/value>='2020-04-02T11:00Z' and
m/data[at0001]/items[at0005]/value/value<='2020-04-04T13:00Z')
```
are now supported.
Fixes: https://github.com/ehrbase/project_management/issues/258
> enable datetime comparison by forcing SQL whenever datetime is detected

- tests/Taskfile.yml
- tests/requirements.txt
- tests/robot/QUERY_SERVICE_TESTS/00_AQL_SMOKE_TEST.robot
- tests/robot/QUERY_SERVICE_TESTS/A.1_EXECUTE_AD-HOC_QUERY/A.1__a_Loaded_DB.robot
- tests/robot/QUERY_SERVICE_TESTS/A.1_EXECUTE_AD-HOC_QUERY/A.1__z_Empty_DB.robot
- tests/robot/_resources/keywords/aql_query_keywords.robot
- tests/robot/_resources/keywords/generic_keywords.robot
- tests/robot/_resources/libraries/jsonlib.py
- tests/robot/_resources/test_data_sets/query/aql_queries_valid/B/800_get_composition_by_uid_empty_db.json
- tests/robot/_resources/test_data_sets/query/aql_queries_valid/B/801_get_composition_by_uid_empty_db.json
- tests/robot/_resources/test_data_sets/query/aql_queries_valid/B/802_get_composition_by_uid_empty_db.json
- tests/robot/_resources/test_data_sets/query/aql_queries_valid/B/803_get_composition_by_uid_empty_db.json
- tests/robot/_resources/test_data_sets/valid_templates/minimal/minimal_observation.composition.participations.extdatetimes.ehrbase.json
- tests/run_local_tests.sh
- mainly related to # 176 and  227 but also other issues
- changes in jsonlib.py
- implemented a solution to ignore some _type properties
- compare kw can now take optional arguments
to ignore properties w/ exclude_reqex_paths
- meta and columns.path properties are now ignored by default
- replaced format-strings with the new f-strings
- reformated code w/ autoformater "black"
- **Updates deepdiff to v. 4.3.2 (requires update of your local test dependencies w/** `pip install -r requirements.txt`**)**
- some clean ups in empty_db test suite
- some fixes in aql_keywords resource
added traces to new issues:
- ehrbase/project_management#234
- ehrbase/project_management#235
- ehrbase/project_management#236
removed traces to
- ehrbase/project_management/issues/199
- …
> AQL test updates and fixes

- service/src/main/java/org/ehrbase/aql/sql/queryImpl/JsonbEntryQuery.java
Fix the jsquery for name/value attribute in the WHERE clause
closes: https://github.com/ehrbase/project_management/issues/262
> fix unproper indexing jsquery on name/value

- CHANGELOG.md
- rest-openehr/src/main/java/org/ehrbase/rest/openehr/controller/OpenehrDirectoryController.java
- Add detection for already existing Directory of an EHR
- Respond with 409 - CONFLICT in case of detected folder
Fixes https://github.com/ehrbase/project_management/issues/231
> Add duplicate detection for directory

- CHANGELOG.md
- pom.xml
- rest-ehr-scape/src/main/java/org/ehrbase/rest/ehrscape/responsedata/QueryResponseData.java
- service/src/main/java/org/ehrbase/service/QueryServiceImp.java
Allow duplicate paths in AQL resultset:
```
{
"q": "SELECT o1/data[at0001]/events[at0002]/data[at0003]/items[at0005]/value/value,
o2/data[at0001]/events[at0002]/data[at0003]/items[at0005]/value/value
from EHR e contains composition a contains (observation o1 [openEHR-EHR-OBSERVATION.laboratory_test_result.v1] and observation o2 [openEHR-EHR-OBSERVATION.laboratory_test_result.v1])"
}
```
Returns:
```
{
"q": "SELECT o1/data[at0001]/events[at0002]/data[at0003]/items[at0005]/value/value,\r\n               o2/data[at0001]/events[at0002]/data[at0003]/items[at0005]/value/value\r\n               from EHR e contains composition a contains (observation o1 [openEHR-EHR-OBSERVATION.laboratory_test_result.v1] and observation o2 [openEHR-EHR-OBSERVATION.laboratory_test_result.v1])",
"columns": [
{ …
```
> Allow duplicated column ids in aql results

- base/src/main/resources/db/migration/V31__canonical_composer_encoding.sql
Fix canonical composition plpgsql function to encode composer attribute properly.
addresses item #2 in https://github.com/ehrbase/project_management/issues/331
> Call proper canonical fct for composer

- CHANGELOG.md
- jooq-pq/pom.xml
- pom.xml
- rest-ehr-scape/pom.xml
- rest-openehr/pom.xml
- service/pom.xml
- Adds Junit5 support via spring-boot-starter-test
NOTE: adding spring-boot-starter-test to parent POM provides all required test dependencies (check: https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-test/2.2.6.RELEASE to see what's included)
Moereover there is no need to declare any test dependencies in submodule's POMs!
> Upgrade to Junit5

- base/src/main/resources/db/migration/V33__fix_AQL_time_retrieval.sql
Fix time representation in ehr.js_dv_date_time(datetime TIMESTAMP, timezone TEXT). Make sure it uses the newer ehr.js_dv_date_time(datetime TIMESTAMPTZ, timezone TEXT)
Fixes: https://github.com/ehrbase/project_management/issues/355
> Fixed time drift (was still using a previous fct)

- .docker_scripts/create-ehrbase-user.sh
- .docker_scripts/docker-entrypoint.sh
- .docker_scripts/install-jsquery.sh
- .docker_scripts/install-temporal-tables.sh
- .docker_scripts/prepare-databases.sh
- .dockerignore
- Dockerfile
An EHRbase docker image is created and published on DockerHub regestry:
- Pushes/merges to ~~develop~~ master branch publish a docker image w/ `latest` tag, i.e. **ehrbaseorg/ehrbase:latest**
- Pushes/merges to develop branch publish a docker image w/ `next` tag, i.e. **ehrbaseorg/ehrbase:next**
- Pushes to release-* branches publish a docker image w/ version `1.2.3` tag, i.e. **ehrbaseorg/ehrbase:0.13.0**
- Uses DockerHub infrastructure (no resources of CircleCI used)
- Adds multi stage Dockerfile with scripts to build ehrbase inside a docker container
- closes https://github.com/ehrbase/project_management/issues/333
- closes https://github.com/ehrbase/project_management/issues/342
It was not sufficient to connect our ehrbase-tech-user, instead the "real" owner of the Github Org had to …
> Automatic Docker image releases via DockerHub's Autobuilds

- README.md
- Removes Docker and CI related infos from README
@axelsiebert  This belongs to https://github.com/ehrbase/documentation/pull/12
> [skip ci] Removes Docker and CI related infos from README

- base/src/main/resources/db/migration/V35__term_mapping.sql
- service/src/main/java/org/ehrbase/aql/sql/PathResolver.java
- service/src/main/java/org/ehrbase/aql/sql/queryImpl/EntryAttributeMapper.java
- service/src/main/java/org/ehrbase/aql/sql/queryImpl/JsonbEntryQuery.java
- service/src/main/java/org/ehrbase/aql/sql/queryImpl/attribute/GenericJsonPath.java
- service/src/main/java/org/ehrbase/aql/sql/queryImpl/attribute/concept/ConceptJson.java
- service/src/main/java/org/ehrbase/aql/sql/queryImpl/attribute/concept/ConceptResolver.java
- service/src/main/java/org/ehrbase/aql/sql/queryImpl/attribute/setting/SettingResolver.java
- service/src/main/java/org/ehrbase/aql/sql/queryImpl/value_field/GenericJsonField.java
- service/src/main/java/org/ehrbase/dao/access/interfaces/I_CompositionAccess.java
- service/src/main/java/org/ehrbase/dao/access/interfaces/I_EntryAccess.java
- service/src/main/java/org/ehrbase/dao/access/jooq/ContextAccess.java
- service/src/main/java/org/ehrbase/dao/access/jooq/EntryAccess.java
- service/src/main/java/org/ehrbase/dao/access/jooq/party/PersistedPartyRelated.java
- service/src/main/java/org/ehrbase/dao/access/jooq/rmdatavalue/JooqDvCodedText.java
- service/src/main/java/org/ehrbase/service/PersistentTermMapping.java
- service/src/main/java/org/ehrbase/service/RecordedDvCodedText.java
- service/src/main/java/org/ehrbase/service/RecordedDvText.java
- service/src/test/java/org/ehrbase/aql/sql/QueryProcessorTest.java
- service/src/test/java/org/ehrbase/service/RecordedDvCodedTextTest.java
Refactored PR #232 and fixed some minor bugs.
The changes impact the DB structure (entry.category & event_context.setting are now cast as UDT ehr.dv_coded_text). A migration (V35) implements the required DB changes.
The following is now supported in CRUD and AQL:
```
"category": {
"_type": "DV_CODED_TEXT",
"value": "event",
"defining_code": {
"terminology_id": {
"value": "openehr"
},
"code_string": "433"
},
"mappings": {
"_type": "TERM_MAPPING",
"match": "=",
"purpose": {
"_type": "DV_CODED_TEXT",
"value": "Erfasst",
"defining_code": {
"terminology_id": {
"value": "local"
},
"code_string": "irgendein Purpose"
}
},
"target": {
"terminology_id": {
"value": "SNOMED-CT"
},
"code_string": "345356676789"
}
}
},
```
```
"setting": {
"_type": "DV_CODED_TEXT",
"value": "other care", …
```
> refactors PR 232 for DvCodedText.mappings

- CHANGELOG.md
- service/pom.xml
- service/src/main/resources/application-local.yaml
- Add ipf-atna-spring-boot-starter library
- Configure atna for the local profile in `application-local.yaml`
Fixes [https://github.com/ehrbase/project_management/issues/403](url)
Usage example:
1. Configure the ATNA properties like audit log repository host, port and other in the application.yaml.
See https://oehf.github.io/ipf-docs/docs/boot-atna/
2. Inject the AuditContext bean:
`
@Autowire
private AuditContext auditContext;
`
3. Use it to send audit logs:
`
auditContext.audit( new ApplicationActivityBuilder.ApplicationStart(EventOutcomeIndicator.Success, "Application Started") .getMessage());
`
> Make ATNA logging configurable in EHRbase #403

- CHANGELOG.md
- application/src/main/java/org/ehrbase/application/config/SecurityConfig.java
- Add CORS configuration to expose WWW-Authenticate header on 401 responses
- Allow all sources for CORS
project_management#409
The changes are required to implement the EHRcontrol UI with a detection mechanism for the target authentication method. As specified in the MDN this header should be sent if a request has been rejected by the server due to authorization failed: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/WWW-Authenticate
> Add CORS configuration to security

- service/src/main/java/org/ehrbase/aql/containment/ContainPropositions.java
- service/src/main/java/org/ehrbase/configuration/CacheConfiguration.java
- service/src/main/java/org/ehrbase/service/KnowledgeCacheService.java
- service/src/main/java/org/ehrbase/service/QueryServiceImp.java
- service/src/main/java/org/ehrbase/service/TemplateDBStorageService.java
- service/src/main/java/org/ehrbase/service/TemplateServiceImp.java
Hardened the knowledge Cache against errors:
- Reject templates when query Metadaten can not be build from it
- Allow startup of ehrbase even if there are errors in the knowledge Cache
- during startup remove missing templates form Cache. should fix https://github.com/ehrbase/ehrbase/issues/336
- fixed a "Transaction rolled back because it has been marked as rollback-only" wenn a  IllegalArgumentException was thrown from  knowledge Cache
- treat errors during deserialization from Cache entries as Cache miss  (happens wenn the java class  changed  but old one are on the disc Cache)
closes https://github.com/ehrbase/ehrbase/issues/336
closes https://github.com/ehrbase/project_management/issues/423
> Feature/ehrbase/project management/issues/423 handle errors knowlage

- application/src/main/java/org/ehrbase/application/config/SecurityConfig.java
- Add dedicated permit of authentication credentials to CORS config as it is required.
- Add default permit values for common used safe settings for APIs
> Add CORS auth support

- CHANGELOG.md
- api/src/main/java/org/ehrbase/api/service/StatusService.java
- base/src/main/resources/db/migration/V40__get_system_version_function.sql
- pom.xml
- rest-openehr/src/main/java/org/ehrbase/rest/openehr/controller/StatusController.java
- service/src/main/java/org/ehrbase/dao/access/interfaces/I_DatabaseStatusAccess.java
- service/src/main/java/org/ehrbase/dao/access/jooq/DatabaseStatusAccess.java
- service/src/main/java/org/ehrbase/service/StatusServiceImp.java
- Add endpoint controller to serve from http://${ehrbase_host:port}/ehrbase/rest/openehr/v1/status
- Add DatabaseStatusAccess to retrieve the PostgreSQL server version from running database
- Add stored procedure to migrations to get the full version string from database
- Add service to extract OS, JVM, PostgreSQL and dependency versions from running instance
- Add build property exposure to build process with maven
> Status endpoint for version check

- service/src/main/java/org/ehrbase/aql/sql/queryimpl/attribute/ehr/EhrResolver.java
fix `ehr/time_created/value` to render as VARCHAR instead of JSONB.
This was causing the HTTP body encoding to be truncated as the JSONB field couldn't be interpreted... as a result only the columns before this bad representation were displayed.
related to ongoing tests on https://github.com/ehrbase/project_management/issues/205
> fixed wrong datatype cast for ehr/time_created/value

- Dockerfile
Beta Release v0.15.0 - second try
- fixed postgres version issue in dockerfile which broke Docker Hub build (s. error below)
- turned off Jacoco for mvn build in dockerfile 
```
...
Step 17/89 : RUN apk add --update postgresql=${PG_MAJOR}-r0 build-base git flex bison
---> Running in f6e23724a79c
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/community/x86_64/APKINDEX.tar.gz
[91mERROR: unsatisfiable constraints:
[0m
postgresql-11.11-r0:
breaks: world[postgresql=11.10-r0]
Removing intermediate container f6e23724a79c
The command '/bin/sh -c apk add --update postgresql=${PG_MAJOR}-r0 build-base git flex bison' returned a non-zero code: 1
```
> Beta Release v0.15.0

- service/src/main/java/org/ehrbase/aql/sql/queryimpl/IterativeNode.java
Fix an issue with json array iteration as it could fall on an non-iterable object.
Fixes: https://github.com/ehrbase/project_management/issues/506 (see comment in the issue re particular failing select item)
> ensure json object is not iterated

- base/src/main/resources/db/migration/V49__deal_with_jsonb_empty_resultset.sql
- service/src/main/java/org/ehrbase/aql/sql/binding/LocatableItem.java
- service/src/test/java/org/ehrbase/aql/sql/queryimpl/JsonbEntryQueryTest.java
- service/src/test/java/org/ehrbase/aql/sql/queryimpl/translator/testcase/pg10/jsquery/TestUC16.java
- service/src/test/java/org/ehrbase/aql/sql/queryimpl/translator/testcase/pg10/jsquery/TestUC7.java
- service/src/test/java/org/ehrbase/aql/sql/queryimpl/translator/testcase/pg10/pgsql/TestUC13.java
- service/src/test/java/org/ehrbase/aql/sql/queryimpl/translator/testcase/pg10/pgsql/TestUC16.java
- service/src/test/java/org/ehrbase/aql/sql/queryimpl/translator/testcase/pg10/pgsql/TestUC17.java
- service/src/test/java/org/ehrbase/aql/sql/queryimpl/translator/testcase/pg10/pgsql/TestUC18.java
- service/src/test/java/org/ehrbase/aql/sql/queryimpl/translator/testcase/pg10/pgsql/TestUC22.java
- service/src/test/java/org/ehrbase/aql/sql/queryimpl/translator/testcase/pg10/pgsql/TestUC27.java
- service/src/test/java/org/ehrbase/aql/sql/queryimpl/translator/testcase/pg10/pgsql/TestUC28.java
- service/src/test/java/org/ehrbase/aql/sql/queryimpl/translator/testcase/pg10/pgsql/TestUC29.java
- service/src/test/java/org/ehrbase/aql/sql/queryimpl/translator/testcase/pg10/pgsql/TestUC30.java
- service/src/test/java/org/ehrbase/aql/sql/queryimpl/translator/testcase/pg10/pgsql/TestUC31.java
- service/src/test/java/org/ehrbase/aql/sql/queryimpl/translator/testcase/pg10/pgsql/TestUC32.java
- service/src/test/java/org/ehrbase/aql/sql/queryimpl/translator/testcase/pg10/pgsql/TestUC33.java
- service/src/test/java/org/ehrbase/aql/sql/queryimpl/translator/testcase/pg10/pgsql/TestUC37.java
- service/src/test/java/org/ehrbase/aql/sql/queryimpl/translator/testcase/pg10/pgsql/TestUC38.java
- service/src/test/java/org/ehrbase/aql/sql/queryimpl/translator/testcase/pg10/pgsql/TestUC39.java
- service/src/test/java/org/ehrbase/aql/sql/queryimpl/translator/testcase/pg10/pgsql/TestUC5.java
- service/src/test/java/org/ehrbase/aql/sql/queryimpl/translator/testcase/pg10/pgsql/TestUC6.java
- service/src/test/java/org/ehrbase/aql/sql/queryimpl/translator/testcase/pg10/pgsql/TestUC7.java
- service/src/test/java/org/ehrbase/aql/sql/queryimpl/translator/testcase/pg10/pgsql/TestUC9.java
- service/src/test/java/org/ehrbase/aql/sql/queryimpl/value_field/GenericJsonFieldTest.java
Extended the standard `jsonb_array_element` to return a set of NULL instead of an empty set. The issue with the standard function is that a cartesian product against an empty set is also empty. Hence, a surprisingly empty resultset when selecting multiple values. Please  note that, with an ITEM_STRUCTURE, we often have arrays (f.e. items[at...]) that are implicitly iterated upon. This is similar to an SQL inner JOIN but is not trivially seen when querying it.
Fixes: https://github.com/ehrbase/project_management/issues/510
> allow cartesian product whenever a set is empty

- application/src/main/resources/ehcache.xml
- set the cache persistence flag to false in ehcache.xml configuration
Note:
This approach allows to keep the Cache abstraction level clean (no change in code) and deal with ehcache specific behavior. Cache files in storage (persistent tier) are destroyed upon JVM termination either by a normal exit or following a kill process. The path in this configuration is set to `${java.io.tmpdir}/ehcache` which translate to `/tmp/ehcache` on Linux. During runtime, this directory contains the respective cache files (under `./file`) and a lock dummy file. When the server process terminate, the cache files are then destroyed. 
In production, this setting should be set according to site strategy. This is documented in https://www.ehcache.org/documentation/3.3/xml.html
Fixes: …
> destroy cache on JVM termination

- application/pom.xml
- pom.xml
- service/src/main/java/org/ehrbase/service/KnowledgeCacheService.java
Force retrieval of operational templates from the DB. (NB. this is initially done, at least for AQL, thus performance is not that impacted).
None, this has been observed during tests
> Force retrieval of operational template from DB

- service/src/main/java/org/ehrbase/aql/sql/binding/InSetWhereClause.java
- service/src/main/java/org/ehrbase/aql/sql/binding/WhereBinder.java
- service/src/main/java/org/ehrbase/aql/sql/binding/WhereVariable.java
Temporary (?) hack to "transparently" swap arguments of the MATCHES operator whenever the left operand is actually a set (or a function returning a set). F.e.
```
a_a/data[at0001]/events[at0002]/data[at0005]/items[at0027]/name/value MATCHES {'Ableitung III'}
```
Is internally interpreted as:
```
'Ableitung III' MATCHES {a_a/data[at0001]/events[at0002]/data[at0005]/items[at0027]/name/value}
```
The logic checks whether the left operand requires this transform (that is, it contains json array unnesting using function such as jsonb_array_elements)
NB. `MATCHES` is always converted as `IN` by the AQL->SQL translator (matches is an operator for string operands in the postgresql dialect)
Fixes: https://github.com/ehrbase/project_management/issues/513
> before closing branch

- pom.xml
- service/src/main/java/org/ehrbase/aql/sql/binding/WhereBinder.java
Generalize use of Lateral join for WHERE expression not using MATCHES (or IN) operator. F.e. 
```
a/items[at0001]/value/magnitude > 11.0
```
In this scenario, the left operand may result in multiple values (set). Using the lateral join technique, this statement is now supported.
on going enhancement
> generalize using lateral join

- application/src/test/java/org/ehrbase/application/abac/AbacIntegrationTest.java
Prevents the IT main class to initialize, if the test env var isn't
set to enable the test.
> Adds ABAC IT activation to higher level

- .env.ehrbase
- Dockerfile
- application/src/main/java/org/ehrbase/application/config/ServerConfigImp.java
- application/src/main/resources/application-cloud.yml
- application/src/main/resources/application-docker.yml
- application/src/main/resources/application-local.yml
- base/docker-example/docker-compose.yml
- service/src/main/java/org/ehrbase/service/BaseService.java
- Replace SYSTEM_NAME by SERVER_NODENAME in dockerfile and configuration files
- Cleanup property `system.type` and unused properties from `BaseService` class
Resolves ehrbase/project_management#536
> Replace SYSTEM_NAME by SERVER_NODENAME

- service/src/main/java/org/ehrbase/aql/containment/IdentifierMapper.java
- service/src/main/java/org/ehrbase/aql/sql/QueryProcessor.java
- service/src/main/java/org/ehrbase/aql/sql/QuerySteps.java
- service/src/main/java/org/ehrbase/aql/sql/queryimpl/ObjectQuery.java
This fix force a NULL select (e.g. SELECT 1 ... WHERE 1 = 0) whenever a query refers to a non template defined node. F.e. 
```
SELECT c FROM EHR e CONTAINS COMPOSITION c CONTAINS OBSERVATION
```
applied to a single composition where the template definition doesn't specify such an OBSERVATION. The result then should be NULL and hence empty resultset.
Fixes: https://github.com/ehrbase/project_management/issues/360
> create null select for node not defined in template

- base/src/main/resources/db/migration/V50__folder_audit.sql
**Note**: Bricks all DB instances, that were initialized with migration V50 before. (Clean installs and datasets with non-conflicting data, which were updated to the newest version.)
- Adds active folder audit DB migration
https://github.com/ehrbase/ehrbase/issues/553
> Adds active folder audit DB migration

- .github/workflows/build-multiarch-image-latest.yml
- .github/workflows/build-multiarch-image-next.yml
- .github/workflows/build-multiarch-image-tag.yml
- Dockerfile
- modified Dockerfile to allow multiarch build
- added Github Action workflows to build docker images with the tags 'next', 'latest' and 'release-version'
Initial implementation and tests done in a [playground repo](https://github.com/testautomation/ehrbase).
Check [Github Action builds](https://github.com/testautomation/ehrbase/actions) and experimental [DockerHub results](https://hub.docker.com/repository/docker/ehrbase/buildx) for details.
resolves https://github.com/ehrbase/ehrbase/issues/567
> automated multi arch docker build via Github Actions

- pom.xml
Upgrade openEHR SDK version (NUM Codex project requires the bugfix for terminology validation).
> Upgrade openEHR SDK version

- base/src/main/resources/db/migration/V61_ehr_subject_id_indexing.sql
Optimizes query with a where clause on subject id:
```
e/ehr_id/value 
from EHR e
where e/ehr_status/subject/external_ref/id/value = '30123'
```
An index is built to this specific attribute encoding. See migration code for more details on indexing on function based data extraction and functional indexing. NB. only IMMUTABLE functions can be used in indexes, hence the migration of the corresponding function.
The index creation is using CONCURRENTLY as the indexing process can be significantly long and thus this is done non blocking see https://www.postgresql.org/docs/9.1/sql-createindex.html#SQL-CREATEINDEX-CONCURRENTLY for more on this option.
none specific.
> added subject/id/value index

- service/src/main/java/org/ehrbase/aql/sql/QueryProcessor.java
- service/src/main/java/org/ehrbase/aql/sql/binding/JoinBinder.java
- service/src/main/java/org/ehrbase/aql/sql/queryimpl/attribute/ehr/ehrstatus/SimpleEhrStatusAttribute.java
- service/src/main/java/org/ehrbase/aql/sql/queryimpl/attribute/ehr/ehrstatus/StatusResolver.java
This change adjust the actual JOIN statements depending on whether it's COMPOSITION attributes based or EHR attributes only.
F.e the join initially is:
```
from "ehr"."entry"
right outer join "ehr"."composition" as "composition_join"
on "composition_join"."id" = "ehr"."entry"."composition_id"
right outer join "ehr"."ehr" as "ehr_join"
on "ehr_join"."id" = "composition_join"."ehr_id"
join "ehr"."status" as "status_join"
on "status_join"."ehr_id" = "ehr_join"."id"
join "ehr"."party_identified" as "subject_ref"
on "subject_ref"."id" = "status_join"."party"
```
With this change:
```
from "ehr"."ehr" as "ehr_join"
join "ehr"."status" as "status_join"
on "status_join"."ehr_id" = "ehr_join"."id"
join "ehr"."party_identified" as "subject_ref"
on "subject_ref"."id" = "status_join"."party"
```
In …
> reduce the join depth as required

- .circleci/config.yml
- tests/Taskfile.yml
- tests/robot/_resources/libraries/dockerlib.py
- I've built and deployed a multiarch ehrbase-postgres DB image which is based on postgres-13.4
- modified CI config and Robot test to use the new DB image
NOTE: there is an issue ( porbably caused by Moby's BuildKit (docker buildx) ) which requieres to set a custom PGDATA folder to successfully run a container based on this image, i.e.
```
docker run --name ehrdb \
-e POSTGRES_PASSWORD=postgres \
-e PGDATA=/tmp \
-d -p 5432:5432 \
ehrbase/ehrbase-postgres:13.4
```
> Use multiarch based postgres 13.4 image in CI pipeline

- CHANGELOG.md
- base/src/main/resources/db/migration/V63__add_missing_ehr_folder_fk.sql
- rest-openehr/src/main/java/org/ehrbase/rest/openehr/OpenehrDirectoryController.java
- Adds the missing foreign key constraints betwenn `ehr` and `folder` tables.
- Removes folder reference before deleting folder associated to an EHR
Resolves ehrbase/project_management#318
> Adds missing foreign key and fixes constraint reference when delete

- CHANGELOG.md
- base/src/main/resources/db/migration/V65__fix_dv_date_time_function.sql
- service/src/main/java/org/ehrbase/aql/sql/queryimpl/attribute/TemporalWithTimeZone.java
- service/src/main/java/org/ehrbase/dao/access/jooq/ContextAccess.java
- service/src/main/java/org/ehrbase/service/RecordedDvDateTime.java
- service/src/test/java/org/ehrbase/aql/sql/queryimpl/attribute/TemporalWithTimeZoneTest.java
- service/src/test/java/org/ehrbase/aql/sql/queryimpl/translator/testcase/pg10/pgsql/UC42Test.java
- service/src/test/java/org/ehrbase/aql/sql/queryimpl/translator/testcase/pg10/pgsql/UC4Test.java
- service/src/test/java/org/ehrbase/service/RecordedDvDateTimeTest.java
Fixes the discrepancy using DV_DATE_TIME without timezone between submitted composition and returned values (Get composition/AQL query).
Fixes PEM-455
> Fixes issue with start time without timezone

- application/pom.xml
- Remove `spring-boot-starter-data-jpa` as EHRbase is not using JPA/Hibernate
- Add `spring-boot-starter-jdbc` to keep auto-configuration for the DataSource.
Closes ehrbase/project_management#591 (PEM-517)
> Replaces spring-boot-starter-data-jpa by spring-boot-starter-jdbc

- service/src/main/java/org/ehrbase/aql/sql/binding/CompositionAttribute.java
- service/src/main/java/org/ehrbase/aql/sql/binding/ContextualAttribute.java
- service/src/main/java/org/ehrbase/aql/sql/binding/SelectBinder.java
This fixes an absent aliasing for items in /context/other_context[at0001] as the aliasing was not properly propagated to the resultset definition.
fixes: https://github.com/ehrbase/ehrbase/issues/688
> fix missing alias substitution

- api/pom.xml
- application/pom.xml
- jooq-pq/pom.xml
- pom.xml
- service/pom.xml
Switch to openEHR SDK dependencies published on Maven Central using groupID: `org.ehrbase.openehr.sdk`
> Cdr 15 maven central

- application/src/main/java/org/ehrbase/application/abac/CustomMethodSecurityExpressionRoot.java
- application/src/test/java/org/ehrbase/application/abac/AbacIntegrationTest.java
- application/src/test/java/org/ehrbase/application/abac/FlywayTestConfiguration.java
- application/src/test/resources/application-test.yml
- application/src/test/resources/composition.json
- application/src/test/resources/contribution.json
- application/src/test/resources/ehr_status.json
- rest-openehr/src/main/java/org/ehrbase/rest/openehr/OpenehrEhrController.java
- rest-openehr/src/main/java/org/ehrbase/rest/openehr/OpenehrQueryController.java
- Added integration tests to check if ABAC server is being called after every API call in c787bf7f5e82bef9eda1408c9bcef90d23097ce0
- Fixed the composition in the ABAC Integration test to commit (it was failing with 400)
- Fixed 500 internal server error when EHR does not have subject id with ABAC turned on in 6ede6f2
#690
The following tests are currently failing:
- GET EHR: Does not call ABAC server. Probably not secured with ABAC.
- GET COMPOSITION (here of deleted composition): Does not call ABAC server (maybe works as expected?)
- GET QUERY: Does not call ABAC server. Probably not secured with ABAC.
- GET QUERY WITH MULTIPLE EHRs AND TEMPLATES (incl. posting those): Does not call ABAC server. Probably not secured with ABAC.
> Minor fixes and failing integration tests for ABAC

- .github/workflows/build.yml
Use correct Docker image for the database: `ehrbase/ehrbase-postgres:13.4`
> Use Docker image ehrbase/ehrbase-postgres:13.4

- CHANGELOG.md
- service/src/main/java/org/ehrbase/dao/access/jooq/party/PersistedPartyIdentified.java
Changed the behavior when committing an identified party as in integration test https://github.com/ehrbase/openEHR_SDK/blob/feature/sync/710_party_conflicts/client/src/test/java/org/ehrbase/client/openehrclient/defaultrestclient/ParticipationTestIT.java
Previously, if unresolved in the DB, party was substituted with a party having the same name and ExternalRef ID if any...
Fixes: https://github.com/ehrbase/ehrbase/issues/710
> changed behavior for conflicting identified parties.

- CHANGELOG.md
- service/src/main/antlr4/org/ehrbase/aql/parser/Aql.g4
- service/src/main/java/org/ehrbase/aql/compiler/QueryCompilerPass2.java
- service/src/test/java/org/ehrbase/aql/compiler/QueryCompilerPass2Test.java
Add default sort direction (ASC) to ORDER BY clause.
Fixes #689
> Fixes default ASC direction for ORDER BY clause

- CHANGELOG.md
- service/src/main/antlr4/org/ehrbase/aql/parser/Aql.g4
- service/src/test/java/org/ehrbase/aql/compiler/QueryCompilerPass2Test.java
Add support for ORDER BY and LIMIT clauses in any order
- Fixes #774 
- CDR-315
> Support for ORDER BY and LIMIT clauses in any order

- pom.xml
- Define UTF-8 encoding in the the POM file as the following has been removed:
```xml
<parent>
<groupId>org.springframework.boot</groupId>
<artifactId>spring-boot-starter-parent</artifactId>
<version>2.4.0</version>
</parent>
``` 
Fix UTF-8 encoding issue
> Fix issue with encoding

- CHANGELOG.md
- rest-ehr-scape/src/main/java/org/ehrbase/rest/ehrscape/controller/EhrController.java
- Implicitly fill missing attributes in EhrScape PUT EHR_STATUS
- Consistency of create EHR and update EHR_Status endpoints in EhrScape EHR endpoints
Fixes CDR-381
> CDR-381: Fix ecis PUT for ehr_status

- .github/workflows/build-multiarch-image-next.yml
Build EHRbase Docker image (ehrbase:next) when a new openEHR SDK SNAPSHOT is published.
CDR-322
> Build EHRbase Docker image when a new SDK SNAPSHOT is published

- service/src/main/java/org/ehrbase/aql/sql/binding/JoinBinder.java
Changed join quality to allow null values in the right member as NULL is valid for an optional health care facility attribute.
Fixes: CR #848
> allow null value for health facility

- CHANGELOG.md
- base/src/main/resources/db/migration/V70__add_index_to_party_identified.sql
- Added a new Flyway migration to create a new index on the `party_identified` table to improve the performance of finding EHRs by subject--id
#856
> perf: add index to improve find EHR by subject-id

- service/src/main/java/org/ehrbase/aql/sql/QuerySteps.java
This issue is related to CDR-419#AQL query without where clause produces NPE
- First change
> Added null safe checks

- tests/robot/COMPOSITION_TESTS/CREATE_COMPOSITION/B.6.s_create_composition_dv_parsable_open_constraint.robot
- tests/robot/COMPOSITION_TESTS/CREATE_COMPOSITION/B.6.t_create_composition_dv_multimedia_open_constraint.robot
- capture 404 not found in case of delete composition and template
- skip to next keywords/test cases and log message in case of 404 was returned
> fix: capture 404 not found in case of delete composition and template

- .gitignore
- Add tests/ folder to .gitignore file
- tests/ folder should be empty in EHRBase repo, as Robot scripts and their configuration is stored in another Github repo (integration-tests)
> fix: provide tests folder into .gitignore file

- .circleci/config.yml
- CHANGELOG.md
- base/src/main/resources/db/migration/V76__move_deleted_participations_to_history.sql
- service/src/main/java/org/ehrbase/dao/access/jooq/ContextAccess.java
- replace old participations on updating an event_context for correct representation in all composition versions
> CDR-647 remove old participations on event_context update

- base/db-setup/migrate_to_cloud_db_setup.sql
Updating the `migrate_to_cloud_db_setup.sql` script to so that it doesn't create a `versioning_trigger` on the `ehr.audit_details` table. There is not a history table (`ehr.audit_details_history`) so it appears like the trigger here is incorrect. 
There's no related issue. We had run the script which resulted in us having a trigger on the `audit_details` table that was causing us an error when we tried to create an EHR as the trigger couldn't write to the non-existent `ehr.audit_details_history` table.
I'm not sure we need to include anything in the changelog here. The change is just to avoid anyone else running the migration script and being affected by the same issue.
> fix: removing non required trigger on audit details table

- rest-openehr/src/main/java/org/ehrbase/rest/BaseController.java
- rest-openehr/src/main/java/org/ehrbase/rest/openehr/OpenehrCompositionController.java
- rest-openehr/src/main/java/org/ehrbase/rest/openehr/OpenehrDirectoryController.java
- service/src/main/java/org/ehrbase/repository/EhrFolderRepository.java
- service/src/main/java/org/ehrbase/service/DirectoryServiceImp.java
- service/src/main/java/org/ehrbase/service/EhrServiceImp.java
-simplified handling of version_at_time parameter
-introduced term 'head' for non-history ("active") folders -fail cleanly when branched versions are provided
-explicitly handle ehrFoldersIdx in Repository
-more readable union queries
-fix: same sysPeriod values in all folders of a version -fix: coordinate sysPeriod values between versions -fix: sysPeriod: min. 1 microsecond between upper and lower
> CDR-690 folder fixes + cleanup

- application/src/main/java/org/ehrbase/application/config/SwaggerConfiguration.java
- application/src/main/java/org/ehrbase/application/config/security/OAuth2SecurityConfiguration.java
- bom/pom.xml
- rest-ehr-scape/pom.xml
- rest-openehr/pom.xml
- Update Swagger UI dependency to work with Spring Boot 3
- Remove deprecate from Oauth Security Configuration
> Enabled swagger ui working with Spring Boot 3

- sonar-project.properties
Sonar project analysis is not going over the plugin path. Added it to the analysis.
> Add plugin path to sonar-project.properties

- application/src/main/java/org/ehrbase/application/config/security/BasicAuthSecurityConfiguration.java
- application/src/main/java/org/ehrbase/application/config/security/OAuth2SecurityConfiguration.java
Add explicit ant matcher wrapper around ant expressions in the Basic and OAuth2 Security Configs.
```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration': Unsatisfied dependency expressed through method 'setFilterChains' parameter 0: Error creating bean with name 'filterChain' defined in class path resource [org/ehrbase/application/config/security/BasicAuthSecurityConfiguration.class]: Failed to instantiate [org.springframework.security.web.SecurityFilterChain]: Factory method 'filterChain' threw exception with message: This method cannot decide whether these patterns are Spring MVC patterns or not. If this endpoint is a Spring MVC endpoint, please use …
```
> Add explicit ant matcher wrappers in the auth security configs

- CHANGELOG.md
- service/src/main/java/org/ehrbase/cache/CacheConfiguration.java
- service/src/main/java/org/ehrbase/cache/CacheProvider.java
- service/src/main/java/org/ehrbase/repository/StoredQueryRepository.java
- service/src/main/java/org/ehrbase/service/StoredQueryServiceImp.java
- service/src/main/java/org/ehrbase/util/StoredQueryQualifiedName.java
- service/src/test/java/org/ehrbase/service/StoredQueryServiceTest.java
- service/src/test/java/org/ehrbase/util/StoredQueryQualifiedNameTest.java
Add a new cache for stored queries.
* Split caffeine cache customization and configuration
* Aligned the `StoredQuertyRepository` to only accept `StoredQueryQualifiedName`
* Added unit tests for `StoredQueryService` functionalities
Correct documentation and links to https://specifications.openehr.org/releases/SM/latest/openehr_platform.html#_query_formalism
> CDR-1339 Add cache for stored queries

- .github/workflows/build-and-test-postgres.yml
Prevent sonar anylize and publish in case the git actor is dependabot. The reason for this is that the bot does not have access to the secrets -> [GitHub Actions: Workflows triggered by Dependabot PRs will run with read-only permissions](https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/).
> CDR-1379 Prevent sonar run for dependabot git actor

- CHANGELOG.md
- configuration/src/main/java/org/ehrbase/configuration/exception/DefaultExceptionHandler.java
- rest-ehr-scape/src/main/java/org/ehrbase/rest/ehrscape/controller/CompositionController.java
- rest-ehr-scape/src/main/java/org/ehrbase/rest/ehrscape/controller/TemplateController.java
- rest-openehr/src/main/java/org/ehrbase/rest/admin/AdminContributionController.java
Admin Delete for contributions is not supported with EHRbase 2.0.0.
This PR takes care of nicely handling the UnsupportedOperationException.
> Add default handler for Unsupported operations

- rest-openehr/src/main/java/org/ehrbase/rest/admin/AdminQueryController.java
Rename the AdminDefinitionController to AdminQueryController for consistency
> Rename the AdminDefinitionController to AdminQueryController for consistency

- .github/workflows/build_and_test.yml
Looks like, the test reporter does not have enough permission to create the junit/robot reports for a PR, that is not created by an ehrbase org member. See -> https://github.com/ehrbase/ehrbase/pull/1303
> Add permissions for dorny/test-reporter and robot reporter

- .github/workflows/build_and_test.yml
Grant read on contents and actions for the dorney test-report action. This allows workflows triggered for PRs  from forked repositories to collect test results. 
Currently failing -> https://github.com/ehrbase/ehrbase/pull/1303.
Permissions overview:
actions:read -> https://docs.github.com/en/rest/authentication/permissions-required-for-github-apps?apiVersion=2022-11-28#repository-permissions-for-actions
contents:read -> https://docs.github.com/en/rest/authentication/permissions-required-for-github-apps?apiVersion=2022-11-28#repository-permissions-for-contents
> Adjust permission for dorney test-reporter

- .github/workflows/build_and_test.yml
Use PERSONAL_ACCESS_TOKEN for reporting the Robot Report
> Change from GITHUB_TOKEN to PERSONAL_ACCESS_TOKEN

- .github/workflows/collect-junit-results.yml
Due to the fact that we trick out dorny/test-reporter by pre-downloading the reports and not using an artifact, it now need the whole github checkout to be present.
> Perform git checkout for JUnit collect workflow

- aql-engine/src/main/java/org/ehrbase/openehr/aqlengine/sql/AqlSqlQueryBuilder.java
Use `EXPLAIN (ANALYZE, ...)` instead of `EXPLAIN ANALYZE` to be able to pass arguments.
depends on: https://github.com/ehrbase/ehrbase/pull/1325
> CDR-1438 Fix postgres explain analyze

- CHANGELOG.md
- Dockerfile
- docker-compose.yml
- tests/DockerfileTest
- tests/docker-compose-int-test.yml
- Create a `ehrbase` dedicated non-root user to run the container.
- Suppress warning about deprecated `version` in Docker Compose files
Closes #1335
> Create dedicated ehrbase use to run the container

- CHANGELOG.md
- rest-openehr/src/main/java/org/ehrbase/rest/BaseController.java
- rest-openehr/src/main/java/org/ehrbase/rest/openehr/OpenehrDirectoryController.java
- rest-openehr/src/main/java/org/ehrbase/rest/openehr/OpenehrTemplateController.java
- rest-openehr/src/main/java/org/ehrbase/rest/openehr/format/CompositionRepresentation.java
- rest-openehr/src/main/java/org/ehrbase/rest/openehr/specification/TemplateApiSpecification.java
- rest-openehr/src/test/java/org/ehrbase/rest/openehr/OpenehrTemplateControllerTest.java
- service/src/main/java/org/ehrbase/service/TemplateServiceImp.java
* Correct supported content types
* ADL 1.4 POST Content-Type and Accept only `application/xml`
* ADL 1.4 GET  Accept `application/xml`, `application/json`, `application/openehr.wt+json`
* Deprecate `/adl1.4/{template_id}/webtemplate`  because it's now supported using ADL 1.4 GET
* Ensure HTTP `406` is returned in case the requested ADL 1.4 Template is not a valid XML 
* Refactor response handling
* Removed dead code from `BaseController`
> [CDR-1471] Align template controller with latest spec

- .github/workflows/release.yml
- bom/pom.xml
- Ensure the SDK is not checked out and build during release
- Add new profile that checks for -SNAPSHOT deps
- Run -SNAPSHOT check before starting the release build
> [CDR-909] Make release pipeline independent from SDK release

- bom/pom.xml
- configuration/src/test/java/org/ehrbase/configuration/config/security/ManagementSecurityConfigurationIT.java
Prometheus to 1.13 broke actuator endpoint -> see https://github.com/micrometer-metrics/micrometer/issues/5103
> Let spring decide which prometheus version is used

- CHANGELOG.md
- configuration/src/main/java/org/ehrbase/configuration/config/security/SecurityConfigBasicAuth.java
- configuration/src/main/java/org/ehrbase/configuration/config/security/SecurityConfigOAuth2.java
Enable user access to the welcome page while authentication is enabled.
Permit DispatcherType.FORWARD and DispatcherType.ERROR in both OAuth2 and BasicAuth configurations. Also added permissions for the welcome page and images, ensuring better error handling and user access to welcome resources.
No issue was reported
> Enable user access to the welcome page while authentication is enabled

- jooq-pg/pom.xml
- pom.xml
Allow to configure maven build DB startup timeout.
> CDR-1614 Make build db timeout configurable

- jooq-pg/pom.xml
Preventing docker container name clashes during parallel builds by letting docker assign a random name
> Use a random container name during build

- application/pom.xml
- application/src/main/resources/banner-cli.txt
- application/src/main/resources/banner.txt
Fix missing EHRbase app version in banner.txt by using resource filtering instead of property.
> Fix banner app version by using resource filtering

- CHANGELOG.md
- bom/pom.xml
- configuration/pom.xml
- configuration/src/main/java/org/ehrbase/configuration/config/flyway/MigrationStrategyConfig.java
- configuration/src/main/resources/application.yml
- jooq-pg/pom.xml
Update to Flyway V11.
Changed flyway config to gracefully fail in case an "older" ehrbase version is deployed against a newer database version.
In such cases EHRBase will now fail with the following message
```
Caused by: org.flywaydb.core.api.exception.FlywayValidateException: Validate failed: Migrations have failed validation
Detected applied migration not resolved locally: 20.
If you removed this migration intentionally, run repair to mark the migration as deleted.
Need more flexibility with validation rules? Learn more: https://rd.gt/3AbJUZE
```
An Alternative solution for https://github.com/ehrbase/ehrbase/pull/1449
> CDR-1667 Update flyway to V11 to gracefully exit on future db version

- .github/workflows/job-maven-publish.yml
- CHANGELOG.md
- bom/pom.xml
- pom.xml
Publishing artifacts directly to Central Sonatype because of ossrh sunset.
https://central.sonatype.org/news/20250326_ossrh_sunset/
> Start preparing changes for sonatype migration

- api/pom.xml
- application/pom.xml
- aql-engine/pom.xml
- bom/pom.xml
- cli/pom.xml
- configuration/pom.xml
- jooq-pg/pom.xml
- plugin/pom.xml
- pom.xml
- rest-ehr-scape/pom.xml
- rest-openehr/pom.xml
- rm-db-format/pom.xml
- service/pom.xml
- test-coverage/pom.xml
The new sonatype central deployment is more strict when it comes to releases.
Added names to all modules and removed not needed dependencies
> Fix pom issues for release

- CHANGELOG.md
- api/src/main/java/org/ehrbase/api/dto/AqlQueryRequest.java
- api/src/test/java/org/ehrbase/api/dto/AqlQueryRequestTest.java
- aql-engine/src/main/java/org/ehrbase/openehr/aqlengine/service/AqlQueryServiceImp.java
- aql-engine/src/test/java/org/ehrbase/openehr/aqlengine/AqlLimitPostProcessorTest.java
- rest-openehr/src/main/java/org/ehrbase/rest/openehr/OpenehrQueryController.java
- rest-openehr/src/test/java/org/ehrbase/rest/openehr/OpenehrQueryControllerTest.java
Instead of parsing the AQL string in the AqlService service - this step is not preformed by the AqlQueryRequest so that an already parsed query can be passed down to the service.
> Parse AQL string before passing to service

- CHANGELOG.md
- UPDATING.md
- aql-engine/src/main/java/org/ehrbase/openehr/aqlengine/AqlConfigurationProperties.java
- aql-engine/src/main/java/org/ehrbase/openehr/aqlengine/asl/AqlSqlLayer.java
- aql-engine/src/main/java/org/ehrbase/openehr/aqlengine/asl/AslFromCreator.java
- aql-engine/src/main/java/org/ehrbase/openehr/aqlengine/asl/AslUtils.java
- aql-engine/src/main/java/org/ehrbase/openehr/aqlengine/featurecheck/FromCheck.java
- aql-engine/src/main/java/org/ehrbase/openehr/aqlengine/pathanalysis/PathCohesionAnalysis.java
- aql-engine/src/main/java/org/ehrbase/openehr/aqlengine/querywrapper/AqlQueryWrapper.java
- aql-engine/src/main/java/org/ehrbase/openehr/aqlengine/querywrapper/contains/ContainsWrapper.java
- aql-engine/src/main/java/org/ehrbase/openehr/aqlengine/querywrapper/contains/RmContainsWrapper.java
- aql-engine/src/main/java/org/ehrbase/openehr/aqlengine/querywrapper/contains/VersionContainsWrapper.java
- aql-engine/src/test/java/org/ehrbase/openehr/aqlengine/asl/AqlSqlLayerTest.java
- aql-engine/src/test/java/org/ehrbase/openehr/aqlengine/asl/AslCleanupPostProcessorTest.java
- aql-engine/src/test/java/org/ehrbase/openehr/aqlengine/asl/AslFromCreatorTest.java
- aql-engine/src/test/java/org/ehrbase/openehr/aqlengine/asl/AslGraphTest.java
- aql-engine/src/test/java/org/ehrbase/openehr/aqlengine/featurecheck/AqlQueryFeatureCheckTest.java
- aql-engine/src/test/java/org/ehrbase/openehr/aqlengine/sql/AqlSqlQueryBuilderTest.java
- aql-engine/src/test/java/org/ehrbase/openehr/util/TestConfig.java
- configuration/src/main/resources/application.yml
> Improve CONTAINS expression semantics when using at-code predicates.
If the parent CONTAINS expression is an archetype, it must be located within that archetype.
If the parent CONTAINS expression is an at-code, it must be located within the same parent archetype and be a descendant.
> Contains expression semantics
