- tests/README.md
removes EtherCIS from test's README
@Geisterfalle
> #22 cleans up test's readme

- .gitignore
- tests/robot/_resources/libraries/jsonlib.py
- tests/robot/_resources/libraries/jsonlib_test.py
> adds 100 % code coverage and more doctests to jsonlib

- tests/robot/_resources/keywords/template_opt1.4_keywords.robot
solves issue ehrbase/project_management#33
> fixes XML validation issue in tests - ehrbase/project_management#33

- .circleci/settings.xml
- pom.xml
No more failed 'mvn install' because of missing gpg key. Signing now needs to be triggered by activating profile 'ossrh'.
> EHR-278 gpg signing now needs to be activated with profile ossrh

- service/src/main/java/org/ehrbase/dao/access/interfaces/I_DomainAccess.java
- service/src/main/java/org/ehrbase/dao/access/jooq/CompositionAccess.java
- service/src/main/java/org/ehrbase/dao/access/support/DataAccess.java
Following CI tests (and test/usage from https://github.com/grantforrester-nes). Many thanks for the contribution!
> integrated changes from PR #62 (allow full checking in CI)

- .circleci/config.yml
- unit and integration test now run on every commit
NOTE: release workflow can now be redesigned properly
> Updates CI pipeline to solve: ehrbase/project_management#99

- tests/dbtruncate.sh
- tests/robot/_resources/test_data_sets/data_load/compositions/minimal_action2_1.composition.json
- tests/robot/_resources/test_data_sets/data_load/compositions/minimal_action2_2.composition.json
- tests/robot/_resources/test_data_sets/data_load/compositions/minimal_action2_3.composition.json
- tests/robot/_resources/test_data_sets/query/expected_results/empty_db/A/603_get_ehrs_by_contains_composition_contains_entry_with_archetype.json
- tests/robot/_resources/test_data_sets/query/expected_results/empty_db/B/603_get_compositions_by_contains_entry_with_archetype_from_all_ehrs.json
- tests/robot/_resources/test_data_sets/query/expected_results/loaded_db/A/603_get_ehrs_by_contains_composition_contains_entry_with_archetype.json
- tests/robot/_resources/test_data_sets/query/expected_results/loaded_db/B/603_get_compositions_by_contains_entry_with_archetype_from_all_ehrs.json
- tests/robot/_resources/test_data_sets/query/expected_results/loaded_db/C/303_get_entries_with_type_from_ehr_with_uid_contains_compositions_with_archetype_from_all_ehrs.json
@testautomation this includes the action compositions and the queries were updated too.
> ehrbase/project_management#98 added ACTION examples and updated AQL test suite data

- validation/src/main/java/org/ehrbase/validation/terminology/ItemStructureVisitor.java
- validation/src/test/java/org/ehrbase/validation/ItemStructureVisitorTest.java
- validation/src/test/resources/composition/RIPPLE-ConformanceTest_invalid_other_context_mm_type.xml
This add the validation for composition/context/other_context
> added validation of other_context

- service/src/main/java/org/ehrbase/aql/sql/queryImpl/attribute/system/SystemResolver.java
> added resolution of ehr/system_id in AQL

- tests/robot/_resources/keywords/directory_keywords.robot
- marks more impacted tests as not-ready
fixes https://github.com/ehrbase/project_management/issues/150
> Adds bug tace # 148

- serialisation/src/main/java/org/ehrbase/serialisation/CompositionSerializer.java
- serialisation/src/main/java/org/ehrbase/serialisation/RawJson.java
- service/src/main/java/org/ehrbase/service/CompositionServiceImp.java
- tests/robot/COMPOSITION_TESTS/JSON2/B.6.e_alternative_flow_4_create_new_invalid_persistent_COMPOSITION.robot
- tests/robot/COMPOSITION_TESTS/XML2/x.B.6.e_alternative_flow_4_create_new_invalid_persistent_COMPOSITION.robot
~This is a fix for issue 126~
fixes https://github.com/ehrbase/project_management/issues/126
> changed the exception pattern and detection of missing attribute

- tests/robot/DIRECTORY_TESTS/A.4_GET_DIRECTORY/A.4__c._EHR_with_complex_directory_structure_and_item.robot
- tests/robot/KNOWLEDGE_TESTS/C.1.b_validate_invalid_OPTs.robot
- tests/robot/KNOWLEDGE_TESTS/C.2.b_upload_invalid_OPTs.robot
- tests/robot/QUERY_SERVICE_TESTS/A.1_EXECUTE_AD-HOC_QUERY/A.1__a_Loaded_DB.robot
- tests/robot/QUERY_SERVICE_TESTS/A.1_EXECUTE_AD-HOC_QUERY/A.1__z_Empty_DB.robot
- tests/robot/_resources/keywords/ehr_keywords.robot
adds new bug trace
- ehrbase/project_management#171
removed bug traces to fixed issues
- fixed ehrbase/project_management#96
- fixed ehrbase/project_management#120
- fixed ehrbase/project_management#108
- fixed ehrbase/project_management#105
- fixed ehrbase/project_management#110
- fixed ehrbase/project_management#83
- fixed ehrbase/project_management#43
FYI @Geisterfalle
> 28 test status overview

- api/src/main/java/org/ehrbase/api/service/ValidationService.java
- service/src/main/java/org/ehrbase/service/CompositionServiceImp.java
- service/src/main/java/org/ehrbase/service/ValidationServiceImp.java
- service/src/test/java/org/ehrbase/service/ValidationServiceTest.java
Quick fixes to check that composition mandatory attributes are there
> check mandatory elements in composition

- README.md
- application/Dockerfile
- Update java runtime version in Dockerfile
- Add documentation on usage with new PostgreSQL container
Closes #65
> ehrbase/ehrbase#65 Docker Java 11

- service/src/main/java/org/ehrbase/aql/compiler/WhereVisitor.java
This fixes the NullPointerException message to be more meaningful:
```
{
"error": "WHERE variable should be a path, found:'uid'",
"status": "Bad Request"
}
```
> throws an exception whenever not using a path in WHERE

- tests/robot/QUERY_SERVICE_TESTS/A.1_EXECUTE_AD-HOC_QUERY/A.1__a_Loaded_DB.robot
- tests/robot/_resources/test_data_sets/data_load/compositions/minimal_action2_1.composition.json
- tests/robot/_resources/test_data_sets/data_load/compositions/minimal_action2_2.composition.json
- tests/robot/_resources/test_data_sets/data_load/compositions/minimal_action2_3.composition.json
- tests/robot/_resources/test_data_sets/query/data_load/compositions/minimal_action2_1.composition.json
- tests/robot/_resources/test_data_sets/query/data_load/compositions/minimal_action2_2.composition.json
- tests/robot/_resources/test_data_sets/query/data_load/compositions/minimal_action2_3.composition.json
- tests/robot/_resources/test_data_sets/valid_templates/minimal/minimal_action_2.instance.composition.json
- tests/robot/_resources/test_data_sets/valid_templates/minimal/minimal_action_2.instance.composition.xml
- tests/robot/_resources/test_data_sets/valid_templates/minimal/minimal_action_2.instance.version.xml
fixes https://github.com/ehrbase/project_management/issues/102
fixes https://github.com/ehrbase/project_management/issues/104
> modified category value to match english definitions

- service/src/main/java/org/ehrbase/aql/sql/postprocessing/RawJsonTransform.java
Following comment from @ppazos when using JMeter, removed this message
> Removed noisy 'Hum'

- tests/robot/COMPOSITION_TESTS/JSON1/B.5.a_main_flow_get_existing_VERSIONED_COMPOSITION.robot
- tests/robot/COMPOSITION_TESTS/XML1/x.B.4.b_alternative_flow_1_get_existing_COMPOSITION_at_version_VERSION_doesnt_exists.robot
- tests/robot/COMPOSITION_TESTS/XML1/x.B.4.c_alternative_flow_2_get_COMPOSITION_at_version_EHR_doesnt_exist.robot
- tests/robot/COMPOSITION_TESTS/XML2/x.B.7.c_alternative_flow_2_update_a_non_existent_COMPOSITION.robot
- tests/robot/COMPOSITION_TESTS/XML2/x.B.8.c_alternative_flow_1_delete_non_existent_COMPOSITION.robot
- tests/robot/_resources/keywords/composition_keywords.robot
- tests/robot/_resources/keywords/contribution_keywords.robot
- tests/robot/_resources/keywords/directory_keywords.robot
- tests/robot/_resources/keywords/template_opt1.4_keywords.robot
- resolves https://github.com/ehrbase/project_management/issues/167
- applies some minor fixes and enhancements
> Removes explicit error message checks from all tests

- tests/Taskfile.yml
- tests/robot/DIRECTORY_TESTS/A.10_GET_VERSIONED_DIRECTORY/A.10__b._EHR_has_two_versions_of_directory.robot
- tests/robot/DIRECTORY_TESTS/A.2_HAS_PATH/A.2__b._EHR_with_directory.robot
- tests/robot/DIRECTORY_TESTS/A.2_HAS_PATH/A.2__c._EHR_with_given_folder_structure.robot
- tests/robot/DIRECTORY_TESTS/A.4_GET_DIRECTORY/A.4__b._EHR_with_directory.robot
- tests/robot/DIRECTORY_TESTS/A.8_HAS_DIRECTORY_VERSION/A.8__b._EHR__has_two_versions_of_directory.robot
- tests/robot/DIRECTORY_TESTS/A.9_GET_DIRECTORY_AT_VERSION/A.9__b._EHR_has_two_versions_of_directory.robot
- tests/robot/_resources/keywords/composition_keywords.robot
- tests/robot/_resources/keywords/contribution_keywords.robot
- tests/robot/_resources/keywords/directory_keywords.robot
- tests/robot/_resources/keywords/ehr_keywords.robot
- tests/robot/_resources/test_data_sets/directory/subfolders_in_directory.json
- resolves ehrbase/project_management#165
- removes bug tag ehrbase/project_management#36
- bumped app.jar version in my Taskfile to 0.11.0
- some clean ups
> 165 update directory has path tests

- tests/robot/DIRECTORY_TESTS/A.4_GET_DIRECTORY/A.4__c._EHR_with_complex_directory_structure_and_item.robot
resolves https://github.com/ehrbase/project_management/issues/171
issue is not reproducible any more
> Removes bug tag # 171

- CHANGELOG.md
Bumps changelog to 0.11.0
none
> Bumps changelog to 0.11.0

- validation/src/main/java/org/ehrbase/validation/constraints/wrappers/CDuration.java
~This fixes this specific issue~
fixes https://github.com/ehrbase/project_management/issues/61
> Fix test for Duration and OffsetDateTime

- rest-openehr/src/main/java/org/ehrbase/rest/openehr/response/QueryResponseData.java
- service/src/main/java/org/ehrbase/dao/access/jooq/AqlQueryHandler.java
This fixes the regression with empty results.
- First change
closes: https://github.com/ehrbase/project_management/issues/197
> fix regressions

- tests/robot/CONTRIBUTION_TESTS/C.1_COMMIT_CONTRIBUTION/C.1__e)_Versioning_event_composition.robot
removes bug tag and closes https://github.com/ehrbase/project_management/issues/127
> Removes bug tag # 127

- tests/robot/_resources/test_data_sets/query/aql_queries_valid/A/202_get_ehr_by_id.json
- tests/robot/_resources/test_data_sets/query/aql_queries_valid/A/202_get_ehr_by_id_empty_db.json
- tests/robot/_resources/test_data_sets/query/aql_queries_valid/A/203_get_ehr_by_id_empty_db.json
- tests/robot/_resources/test_data_sets/query/expected_results/empty_db/A/202_get_ehr_by_id_empty_db.json
- tests/robot/_resources/test_data_sets/query/expected_results/empty_db/A/203_get_ehr_by_id_empty_db.json
- tests/robot/_resources/test_data_sets/query/queries_working_file.js
- Fix for AQL datasets, for https://github.com/ehrbase/project_management/issues/107
https://github.com/ehrbase/project_management/issues/107
@testautomation please review
> #107 fixes for query data sets

- service/src/main/java/org/ehrbase/aql/sql/queryImpl/attribute/GenericJsonPath.java
This is a simple fix for this exception
- First change
closes: https://github.com/ehrbase/project_management/issues/196
> fix terminal value test for non DataValue 'value' attribute

- tests/robot/COMPOSITION_TESTS/JSON2/B.6.d_alternative_flow_3_create_new_invalid_event_COMPOSITION.robot
- tests/robot/COMPOSITION_TESTS/XML2/x.B.6.d_alternative_flow_3_create_new_invalid_event_COMPOSITION.robot
- tests/robot/CONTRIBUTION_TESTS/C.1_COMMIT_CONTRIBUTION/C.1__b)_With_invalid_version_composition.robot
- tests/robot/CONTRIBUTION_TESTS/C.1_COMMIT_CONTRIBUTION/C.1__d)_With_multiple_version_composistions.robot
- tests/robot/CONTRIBUTION_TESTS/C.3_HAS_CONTRIBUTION/C.3__d)_EHR_with_non-existent_contribution.robot
- tests/robot/KNOWLEDGE_TESTS/C.1.b_validate_invalid_OPTs.robot
- tests/robot/KNOWLEDGE_TESTS/C.2.b_upload_invalid_OPTs.robot
- removes bugs
- 127
- 61
- removes test for a case unlikely to occur in real life
https://github.com/ehrbase/project_management/issues/28
> 28 test status update

- application/src/main/resources/application.yml
- service/src/main/java/org/ehrbase/aql/compiler/Statements.java
- service/src/main/java/org/ehrbase/dao/access/jooq/TemplateStoreAccess.java
- service/src/main/java/org/ehrbase/service/KnowledgeCacheService.java
- service/src/main/java/org/ehrbase/service/TemplateDBStorageService.java
- service/src/test/java/org/ehrbase/aql/sql/QueryProcessorTest.java
allow overwrite of templates via spring property system.allow-template-overwrite
- First change
Closes ehrbase/project_management#214
> Feature/project management#214 allow template overrwrite

- CHANGELOG.md
- service/src/main/java/org/ehrbase/service/EhrServiceImp.java
- tests/robot/EHR_SERVICE_TESTS/B.1_CREATE_EHR/B.1__a)_New_EHR.robot
Fixes STATUS w/ empty subject bug 
fixes ehrbase/project_management#160
> Fixes STATUS w/ empty subject bug

- README.md
checkout README.md (scroll to bottom) --> https://github.com/ehrbase/ehrbase/tree/feature/Add_Stargazer-Diagramm-to-REAMDE#stargazers-over-time
see --> https://starchart.cc/ehrbase/ehrbase
> Adds diagram of Github stars over time to README

- api/pom.xml
- pom.xml
- serialisation/pom.xml
- service/pom.xml
- terminology/pom.xml
- validation/pom.xml
> fix reflection version

- tests/Taskfile.yml
- tests/robot/EHR_SERVICE_TESTS/B.1_CREATE_EHR/B.1__a)_New_EHR.robot
- tests/robot/QUERY_SERVICE_TESTS/00_AQL_SMOKE_TEST.robot
- tests/robot/QUERY_SERVICE_TESTS/A.1_EXECUTE_AD-HOC_QUERY/A.1__a_Loaded_DB.robot
- tests/robot/QUERY_SERVICE_TESTS/A.1_EXECUTE_AD-HOC_QUERY/A.1__z_Empty_DB.robot
- tests/robot/_resources/keywords/aql_query_keywords.robot
- tests/robot/_resources/test_data_sets/query/aql_queries_valid/D/311_select_data_values_from_all_ehrs_contains_composition_with_archetype.json
- tests/robot/_resources/test_data_sets/query/expected_results/empty_db/D/311_select_data_values_from_all_ehrs_contains_composition_with_archetype.json
- Bumps .jar version in my Taskfile to 0.12.0
- Reverts changes applied to test-data-sets in PR 179 [as suggested by @ppazos in review](https://github.com/ehrbase/ehrbase/pull/179/files/4c2253f04e69c9e72986a74b464b9d20f9c43d70#r401376141)
- Removes AQL test D/311 by tagging it as future
- Removes AQL tests B/800, B/801 by tagging them as future
- Adds bug trace to new issue ehrbase/project_management#225
- Removes bug tags from passing tests
- ehrbase/project_management#160
- ehrbase/project_management#162
> Test Status Update

- tests/robot/_resources/test_data_sets/directory/update/1_create_empty_directory.json
- tests/robot/_resources/test_data_sets/directory/update/2_add_subfolders.json
- tests/robot/_resources/test_data_sets/directory/update/3_add_items.json
Added data sets for a simple flow of creating and updating an EHR directory.
https://github.com/ehrbase/project_management/issues/178
> added data sets for ehrbase/project_management#178

- tests/robot/QUERY_SERVICE_TESTS/00_AQL_SMOKE_TEST.robot
- tests/robot/QUERY_SERVICE_TESTS/A.1_EXECUTE_AD-HOC_QUERY/A.1__a_Loaded_DB.robot
- tests/robot/_resources/keywords/aql_query_keywords.robot
- tests/robot/_resources/test_data_sets/query/data_load/compositions/all_types.composition.json
Fixed one file that I missed before.
fixes ehrbase/project_management#111
> fix data set for ehrbase/project_management#111

- tests/robot/_resources/test_data_sets/query/aql_queries_valid/A/110_get_ehrs_top_5_orderby.json
- tests/robot/_resources/test_data_sets/query/aql_queries_valid/B/106_get_compositions_top_5_orderby.json
- tests/robot/_resources/test_data_sets/query/aql_queries_valid/D/313_select_data_values_from_all_ehrs_contains_composition_with_archetype_top_5_orderby.json
- tests/robot/_resources/test_data_sets/query/expected_results/empty_db/A/107_get_ehrs_top_5.json
- tests/robot/_resources/test_data_sets/query/expected_results/empty_db/A/110_get_ehrs_top_5_orderby.json
- tests/robot/_resources/test_data_sets/query/expected_results/empty_db/B/106_get_compositions_top_5_orderby.json
- tests/robot/_resources/test_data_sets/query/expected_results/empty_db/D/313_select_data_values_from_all_ehrs_contains_composition_with_archetype_top_5_orderby.json
- tests/robot/_resources/test_data_sets/query/expected_results/loaded_db/A/110_get_ehrs_top_5_orderby.json
- tests/robot/_resources/test_data_sets/query/expected_results/loaded_db/B/106_get_compositions_top_5_order_by.json
- tests/robot/_resources/test_data_sets/query/expected_results/loaded_db/D/313_select_data_values_from_all_ehrs_contains_composition_with_archetype_top_5_orderby.json
Added data sets examples for TOP + ORDER BY
resolves https://github.com/ehrbase/project_management/issues/204
> #204 added aql data sets

- tests/robot/EHR_SERVICE_TESTS/B.1_CREATE_EHR/B.1__a)_New_EHR.robot
Updates some EHR_STATUS related tests
- https://github.com/ehrbase/project_management/issues/161
> Updates test related to issue ehrbase/project_management/issues/161

- tests/robot/EHR_SERVICE_TESTS/B.1_CREATE_EHR/B.1__a)_New_EHR.robot
Adds static bug tag 162 to ease rerun of related tests from issue https://github.com/ehrbase/project_management/issues/162
> Adds static bug 162 to ease rerun of related tests

- service/src/main/java/org/ehrbase/aql/sql/queryImpl/attribute/GenericJsonPath.java
- service/src/main/java/org/ehrbase/aql/sql/queryImpl/attribute/partyref/PartyResolver.java
fix AQL query on e/ehr_status/subject/external_ref/id/value
closes: https://github.com/ehrbase/project_management/issues/241
> intermediary commit

- api/src/main/java/org/ehrbase/api/dto/QueryResultDto.java
- rest-openehr/src/main/java/org/ehrbase/rest/openehr/response/QueryResponseData.java
- service/src/main/java/org/ehrbase/aql/sql/AqlResult.java
- service/src/main/java/org/ehrbase/service/QueryServiceImp.java
- service/src/test/java/org/ehrbase/aql/sql/VariableMultiMapTest.java
Duplicated partial paths allowed in the list of columns.
fixes https://github.com/ehrbase/ehrbase/issues/231
> changed bi-directional map by std Map

- service/src/main/java/org/ehrbase/aql/sql/binding/WhereBinder.java
- service/src/main/java/org/ehrbase/aql/sql/binding/WhereJsQueryExpression.java
This fixes the issue whenever the ehr_id/value is specified in the from EHR predicate.
Fixes: #252
> Fix issue when implicit where ehr/id/value is passed from EHR predicate

- tests/Taskfile.yml
- tests/robot/_resources/keywords/ehr_keywords.robot
fixed some uresolved merge conflict in test files
> fixed unresolved merge conflicts

- tests/Taskfile.yml
- tests/robot/_resources/keywords/generic_keywords.robot
- fixed issue where '-v nodocker' flag that can be provided to `robot` command did not worked any more
- and updated server .jar to 0.13.0 in my Taskfile
> fixed issue where '-v nodocker' flag didn't worked

- service/src/main/java/org/ehrbase/aql/sql/queryImpl/attribute/GenericJsonPath.java
- service/src/main/java/org/ehrbase/aql/sql/queryImpl/attribute/partyref/PartyResolver.java
Append missing db suffix to query
Fixes #217
See issue description of #217
> Fix #217 handle external_ref_id

- .circleci/commit-msg
- .circleciignore
related to https://github.com/ehrbase/project_management/issues/322
- adds .circleciignore for blacklisting file/folders
- adds a pre-commit git hook file which you have to copy to .git/hooks locally to take effect 
closes https://github.com/ehrbase/project_management/issues/322
> Adds a .circleciignore file w/ a pre-commit git hook

- .circleci/config.yml
- README.md
- Adds addition workflow to CI config (workflow 3/3)
- refactored most jobs to use docker instead of machine executor
```
WHAT THIS WORKFLOW DOES
=======================
CI kicks in after push (of sync/* branch) to ehrbase repo. It will
1. pull (from sync/123_example-issue), build, test (unit), install SDK (makes SDK available from ~/.m2)
2. build (using locally installed SDK), test (unit) and package ehrbase (.../target/.jar)
3. start ehrbase server (from previously packaged .jar)
4. run SDK's (java) integration tests
5. run EHRbase's (robot) integration tests
6. create robot test report
HOW TO USE THIS WORKFLOW?
=========================
1. create TWO branches "sync/[issue-id]_name branches" respectively
- ehrbase repo       --> i.e.    sync/123_example-issue
- openehr_sdk repo   --> …
```
> Adds CI workflow for synchronised check of simultaneous changes in EHRbase and SDK repository

- .circleci/config.yml
Fixes an issue on CI where some robot test ran before ehrbase server was fully started.
> fixes flaky test on ci

- service/src/main/java/org/ehrbase/aql/sql/queryImpl/EntryAttributeMapper.java
Handle time/value and origin/value AQL query properly.
Fixes: https://github.com/ehrbase/project_management/issues/208#issuecomment-686615420
> fixed unproper formatting for time/value and origin/value

- pom.xml
- Bump of SDK to new version including dep fix (Fixes multi-imports of javax.xml.namespace.qname)
> Adds SDK version bump to fix dependency bug

- pom.xml
> update jackson version

- tests/robot/QUERY_SERVICE_TESTS/00_AQL_SMOKE_TEST.robot
- tests/robot/QUERY_SERVICE_TESTS/A.1_EXECUTE_AD-HOC_QUERY/A.1__a_Loaded_DB.robot
- removed traces of closed issues 236, 340, 355, 356
- added traces to issues 393, 408
> updates bug tags in robot tests

- application/src/main/java/org/ehrbase/application/config/SwaggerConfig.java
- pom.xml
closes https://github.com/ehrbase/openEHR_SDK/issues/118
> update sdk version

- .github/ISSUE_TEMPLATE/defect(robot).md
- .github/ISSUE_TEMPLATE/defect.md
- .github/ISSUE_TEMPLATE/feature-story.md
- .github/ISSUE_TEMPLATE/task.md
- pom.xml
- Adds version information to bug issue template
- Changes advices to be comments in all templates
> Add versions to bug issue

- base/src/main/resources/db/migration/V43__fix_canonical_comp.sql
simple fix to handle composition with no content querying
fix: https://github.com/ehrbase/project_management/issues/461
> fix wrong canonical json query

- tests/robot/ADMIN_TESTS/002-Composition.robot
adds a new test case to admin composition test suite
https://github.com/ehrbase/ehrbase/issues/433
> Adds test case to reproduce #433

- pom.xml
closes https://github.com/ehrbase/project_management/issues/378
> update sdl version

- api/src/main/java/org/ehrbase/api/service/EhrService.java
- rest-openehr/src/main/java/org/ehrbase/rest/openehr/controller/OpenehrVersionedEhrStatusController.java
- service/src/main/java/org/ehrbase/dao/access/interfaces/I_StatusAccess.java
- service/src/main/java/org/ehrbase/dao/access/jooq/StatusAccess.java
- service/src/main/java/org/ehrbase/service/EhrServiceImp.java
- tests/robot/EHR_STATUS_TESTS/C.6_GET_VERSIONED_EHR_STATUS/C.6__D)_Get_Versioned_EHR_STATUS_By_Version.robot
> Fixes versioned ehr_status bug and adds test

- CHANGELOG.md
- README.md
- api/pom.xml
- application/pom.xml
- base/pom.xml
- jooq-pq/pom.xml
- pom.xml
- rest-ehr-scape/pom.xml
- rest-openehr/pom.xml
- service/pom.xml
- test-coverage/pom.xml
> Beta Release v0.15.0

- pom.xml
> [UPDATE] version of SDK to latest commit hash in SDK's develop branch

- pom.xml
updated SDK version to 9863c23
> [UPDATE] sdk version to commit 9863c23

- service/src/main/java/org/ehrbase/aql/sql/binding/ContextualAttribute.java
- service/src/main/java/org/ehrbase/aql/sql/binding/ExpressionField.java
- service/src/main/java/org/ehrbase/aql/sql/binding/LocatableItem.java
- service/src/main/java/org/ehrbase/aql/sql/binding/SelectBinder.java
- service/src/main/java/org/ehrbase/aql/sql/binding/WhereBinder.java
- service/src/main/java/org/ehrbase/aql/sql/queryimpl/JsonbEntryQuery.java
- service/src/main/java/org/ehrbase/aql/sql/queryimpl/attribute/eventcontext/EventContextJson.java
Fix wrong encoding of where variables. Also, deals with set in where construct down in content.
Fixes: https://github.com/ehrbase/project_management/issues/472
Fixes: https://github.com/ehrbase/project_management/issues/473
See https://github.com/ehrbase/project_management/issues/473 for more details on handling sets in WHERE
> fix where field construct

- CHANGELOG.md
- README.md
- api/pom.xml
- application/pom.xml
- base/pom.xml
- jooq-pq/pom.xml
- pom.xml
- rest-ehr-scape/pom.xml
- rest-openehr/pom.xml
- service/pom.xml
- test-coverage/pom.xml
> Updated release version to v0.16.0

- application/src/main/resources/banner.txt
- Adds custom logo
closes https://github.com/ehrbase/project_management/issues/457
> Adds custom logo

- api/pom.xml
- application/pom.xml
- base/pom.xml
- jooq-pq/pom.xml
- pom.xml
- rest-ehr-scape/pom.xml
- rest-openehr/pom.xml
- service/pom.xml
- test-coverage/pom.xml
changed SDK version to <ehrbase.sdk.version>8cf760c</ehrbase.sdk.version>
> patch release v0.16.1

- api/pom.xml
- application/pom.xml
- base/pom.xml
- jooq-pq/pom.xml
- pom.xml
- rest-ehr-scape/pom.xml
- rest-openehr/pom.xml
- service/pom.xml
- test-coverage/pom.xml
SDK update: `<ehrbase.sdk.version>2930e3e</ehrbase.sdk.version>`
> Updated release version to v0.16.3

- api/pom.xml
- application/pom.xml
- base/pom.xml
- ehrbase-log
- jooq-pq/pom.xml
- pom.xml
- rest-ehr-scape/pom.xml
- rest-openehr/pom.xml
- service/pom.xml
- test-coverage/pom.xml
- tests/requirements.txt
- tests/robot/_resources/keywords/generic_keywords.robot
also
- updated a Robot dependency and
- added KW to output EHRbase's startup stack trace in Robot's log
> Updated release version to v0.16.4

- api/pom.xml
- application/pom.xml
- base/pom.xml
- jooq-pq/pom.xml
- pom.xml
- rest-ehr-scape/pom.xml
- rest-openehr/pom.xml
- service/pom.xml
- test-coverage/pom.xml
> [UPDATE] release version to 0.16.5

- rest-openehr/src/main/java/org/ehrbase/rest/openehr/audit/OpenEhrAuditInterceptor.java
- Fixed a bug in the ATNA interceptor
- See also https://github.com/ehrbase/project_management/issues/524
fixes https://github.com/ehrbase/project_management/issues/518
> Adds fix for nullable external ref

- pom.xml
- Updates SDK version to f6a2d50
> Updates SDK version to f6a2d50

- service/src/main/java/org/ehrbase/dao/access/jooq/EntryAccess.java
- service/src/main/java/org/ehrbase/dao/access/jooq/SystemValue.java
add persistence for `composition/archetype_details/rm_version`
Fixes: https://github.com/ehrbase/project_management/issues/463
> add support of rm_version in persistence

- CHANGELOG.md
- README.md
- api/pom.xml
- application/pom.xml
- base/pom.xml
- jooq-pq/pom.xml
- pom.xml
- rest-ehr-scape/pom.xml
- rest-openehr/pom.xml
- service/pom.xml
- test-coverage/pom.xml
Update to release v0.17.0 beta
> Updated release version to v0.17.0

- base/src/main/resources/db/migration/V51__CR_558_560.sql
- service/src/main/java/org/ehrbase/aql/sql/queryimpl/attribute/ehr/ehrstatus/EhrStatusJson.java
- service/src/main/java/org/ehrbase/aql/sql/queryimpl/value_field/GenericJsonField.java
- Added missing attributes when encoding canonical DV_IDENTIFIER
- Create the missing ehr_status/uid when querying with AQL.
- First change
Fixes: #558 
Fixes: #560
> CR 558 & CR 560 fixing

- CHANGELOG.md
- README.md
- api/pom.xml
- application/pom.xml
- base/pom.xml
- jooq-pq/pom.xml
- pom.xml
- rest-ehr-scape/pom.xml
- rest-openehr/pom.xml
- service/pom.xml
- test-coverage/pom.xml
> Updated release version to v0.17.1

- base/src/main/resources/db/migration/V54__fix_subject_encoding.sql
Use SQL canonical encoding fct for subject in ehr_status
Fixes: https://jira.vitagroup.ag/browse/PEA-398
> fix wrong subject encoding

- pom.xml
- Quick version bump to up to date SDK
#575
> Updates SDK version

- CHANGELOG.md
- base/src/main/resources/db/migration/V59__add_party_identified_idx.sql
- service/src/main/java/org/ehrbase/dao/access/jooq/CompositionAccess.java
- service/src/main/java/org/ehrbase/dao/access/jooq/party/PersistedPartyProxy.java
- service/src/main/java/org/ehrbase/service/EhrServiceImp.java
- service/src/main/java/org/ehrbase/util/PartyUtils.java
> Removes SELECT statement when PartyProxy object is empty

- rest-ehr-scape/src/main/java/org/ehrbase/rest/ehrscape/controller/CompositionController.java
Fixes issue with full composition UID and PUT method.
- Fixes #524
- Fixes #513
> Fixes issue with full composition UID and PUT method

- CHANGELOG.md
- service/src/main/java/org/ehrbase/dao/access/interfaces/I_FolderAccess.java
- service/src/main/java/org/ehrbase/dao/access/jooq/FolderAccess.java
- service/src/main/java/org/ehrbase/dao/access/jooq/FolderHistoryAccess.java
- service/src/main/java/org/ehrbase/service/FolderServiceImp.java
Includes `details` in the reponse according to openEHR REST API specification.
Fixes #443
> Fixes #443 - Get Directory missing details

- .circleci/config.yml
- tests/robot/COMPOSITION_TESTS/COMPOSITION_WITH_DIFFERENT_TIME_ZONES/COMPOSITION_JSON_Berlin_time_zone.robot
- tests/robot/COMPOSITION_TESTS/COMPOSITION_WITH_DIFFERENT_TIME_ZONES/COMPOSITION_JSON_no_time_zone.robot
- tests/robot/COMPOSITION_TESTS/COMPOSITION_WITH_DIFFERENT_TIME_ZONES/COMPOSITION_JSON_utc.robot
- tests/robot/COMPOSITION_TESTS/COMPOSITION_WITH_DIFFERENT_TIME_ZONES/__init__.robot
- tests/robot/_resources/keywords/aql_query_keywords.robot
- tests/robot/_resources/test_data_sets/query/aql_queries_valid/get_time_from_ehr.json
- tests/robot/_resources/test_data_sets/query/expected_results/loaded_db/get_time_from_ehr_Berlin_time_zone.json
- tests/robot/_resources/test_data_sets/query/expected_results/loaded_db/get_time_from_ehr_no_time_zone.json
- tests/robot/_resources/test_data_sets/query/expected_results/loaded_db/get_time_from_ehr_utc_time_zone.json
- tests/robot/_resources/test_data_sets/valid_templates/minimal/minimal_observation.composition.participations.extdatetimes_Berlin_time_zone.xml
- tests/robot/_resources/test_data_sets/valid_templates/minimal/minimal_observation.composition.participations.extdatetimes_no_time_zone.xml
- tests/robot/_resources/test_data_sets/valid_templates/minimal/minimal_observation.composition.participations.extdatetimes_utc.xml
> Added test suite for compositions with different time zones

- .github/workflows/build-release.yml
- .github/workflows/build-snapshot.yml
- api/pom.xml
- application/pom.xml
- base/pom.xml
- jooq-pq/pom.xml
- pom.xml
- rest-ehr-scape/pom.xml
- rest-openehr/pom.xml
- service/pom.xml
- test-coverage/pom.xml
Uses GitHub Actions to publish snapshot and release to Maven Central
PEM-314
> Publish snapshot and release to Maven Central

- pom.xml
Fixes issue with action
PEM-314
> Fixes issue with action

- tests/robot/_resources/keywords/composition_keywords.robot
- tests/robot/_resources/keywords/contribution_keywords.robot
- tests/robot/_resources/keywords/directory_keywords.robot
- tests/robot/_resources/keywords/template_opt1.4_keywords.robot
fixes https://github.com/ehrbase/project_management/issues/585
> Replaced depreceated robot get kw

- application/src/main/java/org/ehrbase/application/config/cache/CacheConfiguration.java
- application/src/main/java/org/ehrbase/application/config/cache/CacheInitializer.java
- application/src/main/java/org/ehrbase/application/config/cache/CacheProperties.java
- application/src/main/resources/application.yml
- application/src/main/resources/ehcache.xml
- pom.xml
- service/src/main/java/org/ehrbase/dao/access/interfaces/I_TemplateStoreAccess.java
- service/src/main/java/org/ehrbase/dao/access/jooq/TemplateStoreAccess.java
- service/src/main/java/org/ehrbase/service/KnowledgeCacheService.java
- service/src/main/java/org/ehrbase/service/TemplateDBStorageService.java
- service/src/main/java/org/ehrbase/service/TemplateStorage.java
- service/src/main/java/org/ehrbase/service/ValidationServiceImp.java
- service/src/main/java/org/ehrbase/util/TemplateUtils.java
- service/src/test/java/org/ehrbase/service/CacheRule.java
- service/src/test/java/org/ehrbase/service/KnowledgeCacheServiceTest.java
- service/src/test/java/org/ehrbase/service/TemplateFileStorageService.java
Migrate EHRbase code from JCache API to Spring Cache.
PEM-316
> Pem 316 enhanced caching

- CHANGELOG.md
- pom.xml
> update log4j version

- CHANGELOG.md
- api/pom.xml
- application/pom.xml
- base/pom.xml
- base/src/main/resources/db/migration/V62__add_entry_history_missing_columns.sql
- base/src/main/resources/db/migration/beforeValidate.sql
- jooq-pq/pom.xml
- pom.xml
- rest-ehr-scape/pom.xml
- rest-openehr/pom.xml
- service/pom.xml
- test-coverage/pom.xml
> release v0.18.1

- Dockerfile
Changes to source files will not trigger dependencies re-download
Changes to pom.xml files will do
> DockerFile: cache dependencies

- CHANGELOG.md
- base/src/main/resources/db/migration/beforeMigrate.sql
Add Flyway callback to check the `IntervalStyle` configuration parameter.
CDR-133
> Add callback to check the IntervalStyle setting

- CHANGELOG.md
- api/pom.xml
- jooq-pq/pom.xml
- pom.xml
- service/pom.xml
Upgrade to archie 1.0.4 (using artifacts published on Maven Central)
CDR-156
> Upgrade to archie 1.0.4

- CHANGELOG.md
- rest-ehr-scape/src/main/java/org/ehrbase/rest/ehrscape/controller/CompositionController.java
Fixes wrong status code returned while creating composition using EhrScape API
Fixes ehrbase/project_management/issues/593 (CDR-93)
> Fixes wrong status while flat composition is created

- CHANGELOG.md
- service/src/main/java/org/ehrbase/service/CompositionServiceImp.java
- tests/robot/ADMIN_TESTS/002-Composition.robot
Fix NullPointerException while deleting unknown composition
Closes #433
> Fix NullPointerException while deleting unknown composition

- CHANGELOG.md
- service/src/main/java/org/ehrbase/aql/sql/queryimpl/EntryAttributeMapper.java
- service/src/main/java/org/ehrbase/aql/sql/queryimpl/IterativeNode.java
- service/src/main/java/org/ehrbase/aql/sql/queryimpl/NormalizedOtherParticipations.java
- service/src/main/java/org/ehrbase/aql/sql/queryimpl/NormalizedRmAttributePath.java
Implemented effective other_participations querying as it was not serviced.
fixes: https://github.com/ehrbase/ehrbase/issues/707
> fix querying other_participations

- LICENSE.md
- pom.xml
Remove Apache Velocity dependency from dependency management section.
> Removes Apache Velocity dependency

- api/src/main/java/org/ehrbase/api/service/ValidationService.java
- application/src/main/java/org/ehrbase/application/config/validation/ValidationConfiguration.java
- application/src/main/resources/ehcache.xml
- service/src/main/java/org/ehrbase/cache/CacheOptions.java
- service/src/main/java/org/ehrbase/service/CompositionServiceImp.java
- service/src/main/java/org/ehrbase/service/ContributionServiceImp.java
- service/src/main/java/org/ehrbase/service/EhrServiceImp.java
- service/src/main/java/org/ehrbase/service/ValidationServiceImp.java
- tests/robot/CONTRIBUTION_TESTS/COMMIT_CONTRIBUTION/C.10__Composition_with_non_existent_OPT.robot
Use WebTemplate based validation
CDR-45
> Use WebTemplate based validation

- tests/robot/_resources/keywords/generic_keywords.robot
> Updated github readme links with the current integration test doc link

- tests/robot/COMPOSITION_TESTS/CREATE_COMPOSITION/B.6.a_main_flow_create_new_event_COMPOSITION.robot
- tests/robot/COMPOSITION_TESTS/CREATE_COMPOSITION/B.6.h_main_flow_create_new_event_FLAT_COMPOSITION.robot
- tests/robot/_resources/keywords/composition_keywords.robot
- tests/robot/_resources/test_data_sets/compositions/FLAT/nested.en.v1__full.xml.flat.json
> Removed not-ready tag from some of flat format test cases

- CHANGELOG.md
- application/src/main/java/org/ehrbase/application/config/cache/CacheInitializer.java
- application/src/main/java/org/ehrbase/application/config/security/BasicAuthSecurityConfiguration.java
- application/src/main/java/org/ehrbase/application/config/security/NoOpSecurityConfiguration.java
- application/src/main/java/org/ehrbase/application/config/security/OAuth2SecurityConfiguration.java
- application/src/main/java/org/ehrbase/application/config/validation/ValidationConfiguration.java
- application/src/main/java/org/ehrbase/application/web/LoggingContextFilter.java
- application/src/main/resources/application.yml
- rest-ehr-scape/src/main/java/org/ehrbase/rest/ehrscape/EhrScapeExceptionHandler.java
- rest-ehr-scape/src/main/java/org/ehrbase/rest/ehrscape/controller/BaseController.java
- rest-ehr-scape/src/main/java/org/ehrbase/rest/ehrscape/controller/EhrController.java
- rest-openehr/src/main/java/org/ehrbase/rest/BaseController.java
- rest-openehr/src/main/java/org/ehrbase/rest/DefaultExceptionHandler.java
- rest-openehr/src/main/java/org/ehrbase/rest/openehr/OpenehrCompositionController.java
- service/src/main/java/org/ehrbase/dao/access/jooq/CompositionAccess.java
- service/src/main/java/org/ehrbase/dao/access/jooq/EhrAccess.java
- service/src/main/java/org/ehrbase/dao/access/jooq/EntryAccess.java
- service/src/main/java/org/ehrbase/dao/access/jooq/FolderAccess.java
- service/src/main/java/org/ehrbase/dao/access/jooq/FolderHistoryAccess.java
- service/src/main/java/org/ehrbase/dao/access/jooq/StatusAccess.java
- service/src/main/java/org/ehrbase/service/CompositionServiceImp.java
- service/src/main/java/org/ehrbase/service/ContributionServiceImp.java
- service/src/main/java/org/ehrbase/service/FhirTerminologyServerR4AdaptorImpl.java
- service/src/main/java/org/ehrbase/service/TemplateServiceImp.java
- service/src/main/java/org/ehrbase/service/ValidationServiceImp.java
- tests/robot/ADMIN_TESTS/005-Template.robot
- tests/robot/COMPOSITION_TESTS/VALIDATION/V.2.b_Cardinality_of_SECTION_class.robot
- tests/robot/COMPOSITION_TESTS/VALIDATION/V.2.d_Cardinality_of_ENTRY_class_inside_the_SECTION.robot
- tests/robot/_resources/keywords/contribution_keywords.robot
- Improve exceptions and errors logging
- CDR-28
- CDR-11
> Improve exceptions and errors logging

- rest-ehr-scape/src/main/java/org/ehrbase/rest/ehrscape/EhrScapeExceptionHandler.java
Fix wrong status returned when invalid FLAT composition is sumitted
CDR-11
> Fix wrong status returned when invalid FLAT composition is sumitted

- tests/robot/COMPOSITION_TESTS/GET_COMPOSITION/x.B.5.d_get_FLAT_Composition.robot
> Added round trip flat format test template

- api/src/main/java/org/ehrbase/api/exception/InvalidApiParameterException.java
- api/src/main/java/org/ehrbase/api/service/EhrService.java
- rest-openehr/src/main/java/org/ehrbase/rest/openehr/OpenehrDirectoryController.java
- rest-openehr/src/main/java/org/ehrbase/rest/openehr/OpenehrEhrController.java
- rest-openehr/src/main/java/org/ehrbase/rest/openehr/OpenehrEhrStatusController.java
- rest-openehr/src/main/java/org/ehrbase/rest/openehr/OpenehrQueryController.java
- rest-openehr/src/main/java/org/ehrbase/rest/openehr/OpenehrVersionedCompositionController.java
- rest-openehr/src/main/java/org/ehrbase/rest/openehr/OpenehrVersionedEhrStatusController.java
- rest-openehr/src/main/java/org/ehrbase/rest/openehr/specification/DirectoryApiSpecification.java
- rest-openehr/src/main/java/org/ehrbase/rest/openehr/specification/EhrStatusApiSpecification.java
- rest-openehr/src/main/java/org/ehrbase/rest/openehr/specification/QueryApiSpecification.java
- service/src/main/java/org/ehrbase/aql/compiler/QueryCompilerPass2.java
- service/src/main/java/org/ehrbase/aql/containment/CommonTokenCompare.java
- service/src/main/java/org/ehrbase/aql/containment/ContainsExpressions.java
- service/src/main/java/org/ehrbase/aql/containment/ContainsProposition.java
- service/src/main/java/org/ehrbase/service/CompositionServiceImp.java
- service/src/main/java/org/ehrbase/service/ContributionServiceImp.java
- service/src/main/java/org/ehrbase/service/EhrServiceImp.java
Fix Sonar reliability issues
CDR-224
> Fix Sonar reliability issues

- tests/robot/COMPOSITION_TESTS/CREATE_COMPOSITION/B.6.d_alternative_flow_3_create_new_invalid_event_COMPOSITION.robot
- tests/robot/COMPOSITION_TESTS/CREATE_COMPOSITION/B.6.e_alternative_flow_4_create_new_invalid_persistent_COMPOSITION.robot
closes https://github.com/ehrbase/project_management/issues/596
closes https://github.com/ehrbase/project_management/issues/596
> Removed not ready from test cases for bug 596 and 597

- .github/workflows/jdk-compat.yml
- service/src/main/java/org/ehrbase/aql/sql/binding/LateralJoins.java
- service/src/main/java/org/ehrbase/dao/access/jooq/ContextAccess.java
- Fix issue with Java 17 and JOOQ
- Add new workflow to build the project using Java 11 and 17
- CDR-134
> Fixes issue between Java 17 and JOOQ

- application/src/main/java/org/ehrbase/application/web/ForwardFilter.java
- rest-ehr-scape/src/main/java/org/ehrbase/rest/ehrscape/controller/BaseController.java
- rest-openehr/src/main/java/org/ehrbase/rest/BaseController.java
closes https://github.com/ehrbase/ehrbase/issues/766
> fix location for proxy

- CHANGELOG.md
- service/src/main/java/org/ehrbase/dao/access/jooq/CompositionAccess.java
- Update Composition.feeder_audit on Composition Update
Closes #769 / CDR-309
> Allow update/adding/removal of feeder_audit/links on Composition

- api/src/main/java/org/ehrbase/api/service/QueryService.java
- rest-ehr-scape/src/main/java/org/ehrbase/rest/ehrscape/controller/QueryController.java
- rest-openehr/src/main/java/org/ehrbase/rest/openehr/OpenehrQueryController.java
- service/src/main/java/org/ehrbase/service/QueryServiceImp.java
auditresultmap is now passed as an explicit argument
- First change
> removed auditresultmap from a class member

- rest-openehr/src/main/java/org/ehrbase/rest/openehr/OpenehrQueryController.java
- rest-openehr/src/main/java/org/ehrbase/rest/openehr/RequestAwareAuditResultMapHolder.java
> Fixed issue related to request specific data

- CHANGELOG.md
- pom.xml
> update spring boot to version 2.5.12

- CHANGELOG.md
- api/src/main/java/org/ehrbase/api/service/EhrService.java
- rest-openehr/src/main/java/org/ehrbase/rest/openehr/OpenehrCompositionController.java
- rest-openehr/src/main/java/org/ehrbase/rest/openehr/OpenehrDirectoryController.java
- service/src/main/java/org/ehrbase/dao/access/interfaces/I_EhrAccess.java
- service/src/main/java/org/ehrbase/dao/access/jooq/EhrAccess.java
- service/src/main/java/org/ehrbase/dao/access/util/FolderUtils.java
- service/src/main/java/org/ehrbase/service/CompositionServiceImp.java
- service/src/main/java/org/ehrbase/service/ContributionServiceImp.java
- service/src/main/java/org/ehrbase/service/EhrServiceImp.java
- service/src/main/java/org/ehrbase/service/FolderServiceImp.java
- service/src/test/java/org/ehrbase/dao/access/util/FolderUtilsTest.java
- service/src/test/java/org/ehrbase/service/FolderServiceImpTest.java
- Directory CUD operations check EHR_STATUS.is_modifiable
- Move some misplaced directory logic from Controller to Service
- Composition CUD operations check EHR_STATUS.is_modifiable
CDR-283
> CDR-283 Add is_modifiable semantics

- CHANGELOG.md
- api/src/main/java/org/ehrbase/api/service/TemplateService.java
- pom.xml
- rest-ehr-scape/src/main/java/org/ehrbase/rest/ehrscape/controller/TemplateController.java
- rest-openehr/src/main/java/org/ehrbase/rest/openehr/OpenehrTemplateController.java
- rest-openehr/src/main/java/org/ehrbase/rest/openehr/specification/TemplateApiSpecification.java
- service/pom.xml
- service/src/main/java/org/ehrbase/aql/compiler/AqlErrorHandlerNoRecovery.java
- service/src/main/java/org/ehrbase/service/TemplateServiceImp.java
> #14 add example generator to openehr and ecis template rest resources

- .circleci/config.yml
- Fixed synced-feature-check workflow in CircleCI
N/A
Merged separate reactor builds with workspace-cached .m2 share into a single job sharing an .m2 repository.
> Fixed synced-feature-check workflow in CircleCI

- rest-ehr-scape/src/main/java/org/ehrbase/rest/ehrscape/controller/TemplateController.java
- rest-openehr/src/main/java/org/ehrbase/rest/openehr/OpenehrTemplateController.java
- rest-openehr/src/main/java/org/ehrbase/rest/openehr/specification/TemplateApiSpecification.java
Corrected example message format in TemplateController and OpenehrTemplateController
Closes #809
> #809 Align format of template examples to composition endpoints

- tests/robot/TEMPLATE_TESTS/template_example.robot
- tests/robot/_resources/keywords/composition_keywords.robot
> fix: remove bug loggin in case of XML return of Template Example

- tests/robot/QUERY_SERVICE_TESTS/A.1_EXECUTE_AD-HOC_QUERY/A.1__a_Loaded_DB.robot
- tests/robot/_resources/test_data_sets/query/aql_queries_valid/D/505_select_data_without_composition_and_ehr_criteria.json
> feat: cover with robot test case github issue 808

- CHANGELOG.md
- base/src/main/resources/db/migration/V69__add_unique_constraints.sql
- service/src/main/java/org/ehrbase/dao/access/interfaces/I_CompositionAccess.java
- service/src/main/java/org/ehrbase/dao/access/interfaces/I_EntryAccess.java
- service/src/main/java/org/ehrbase/dao/access/jooq/CompositionAccess.java
- service/src/main/java/org/ehrbase/dao/access/jooq/EntryAccess.java
- service/src/main/java/org/ehrbase/service/CompositionServiceImp.java
- Add unique constraints in Flyway migration scripts
- Update data access layer accordingly
CDR-339
> Cdr 339 unique contraints

- rest-ehr-scape/src/main/java/org/ehrbase/rest/ehrscape/controller/CompositionController.java
Fixes https://github.com/ehrbase/ehrbase/issues/811
> Consistent compositionUid for APIs

- Dockerfile
- bom/pom.xml
- pom.xml
Fix issue using `mvn dependency:go-offline` while building EHRbase Docker images
CDR-374
> Fix issue with mvn dependency:go-offline

- service/src/main/java/org/ehrbase/aql/sql/queryimpl/attribute/FieldResolutionContext.java
Trivial fix to ensure variable alias is correctly propagated into the result.
Fixes: https://github.com/ehrbase/ehrbase/issues/787
> ensure alias is propagated

- .circleci/config.yml
- .mvn/jvm.config
- CHANGELOG.md
- README.md
- api/pom.xml
- base/pom.xml
- jooq-pq/pom.xml
- license-header
- plugin/pom.xml
- pom.xml
- pre-commit.sh
- rest-ehr-scape/pom.xml
- rest-openehr/pom.xml
- service/pom.xml
- test-coverage/pom.xml
- Add spotless maven plugin
- add spotless:check as check for PRs
- CDR-385
> Add spotless plugin, Add codestyle check to workflows

- CHANGELOG.md
- api/src/main/java/org/ehrbase/api/service/EhrService.java
- Fix NPE in EhrService::checkEhrExists
CDR-409
> Fixed NPE in EhrService::checkEhrExists

- tests/robot/EHRSCAPE_TESTS/ehrscape_crud_composition.robot
- tests/robot/TEMPLATE_TESTS/template_example.robot
- tests/robot/_resources/keywords/composition_keywords.robot
- Update scripts in context of fixed CDR-409 and CDR-410 bugs
- Remove bug id logs from test cases
- https://jira.vitagroup.ag/browse/CDR-409
- https://jira.vitagroup.ag/browse/CDR-410
> fix: test fixed bugs cdr-409 and cdr-410

- service/src/main/java/org/ehrbase/aql/sql/QueryProcessor.java
Extracted from https://github.com/ehrbase/ehrbase/pull/807
Prevent NPE in QueryProcessor::buildExplain
> Prevent NPE in QueryProcessor::buildExplain

- tests/robot/EVENT_TRIGGER_TESTS/event_trigger_crud_tests.robot
- tests/robot/_resources/keywords/event_trigger_keywords.robot
- Add tests for DELETE Event Trigger operation
- Change validations for Get all Event Triggers
> feat: add DELETE test for Event Trigger

- CHANGELOG.md
- service/src/main/java/org/ehrbase/dao/access/jooq/FolderAccess.java
closes https://github.com/ehrbase/ehrbase/issues/976
> fix folder update

- CHANGELOG.md
- service/src/main/java/org/ehrbase/dao/access/jooq/AuditDetailsAccess.java
closes https://github.com/ehrbase/ehrbase/issues/988
> CDR-560 add timzone to AuditDetails

- CHANGELOG.md
- rest-openehr/src/main/java/org/ehrbase/rest/openehr/OpenehrCompositionController.java
- rest-openehr/src/main/java/org/ehrbase/rest/openehr/OpenehrDirectoryController.java
- rest-openehr/src/main/java/org/ehrbase/rest/openehr/OpenehrEhrStatusController.java
> unwrap if match additional double quotes

- CHANGELOG.md
- service/src/main/java/org/ehrbase/service/EhrServiceImp.java
- service/src/main/java/org/ehrbase/service/KnowledgeCacheService.java
> empty validation on language

- CHANGELOG.md
- application/src/main/java/org/ehrbase/application/abac/CustomMethodSecurityExpressionRoot.java
- application/src/test/java/org/ehrbase/application/abac/CustomMethodSecurityExpressionRootTest.java
> add abac tenant logic validation

- CHANGELOG.md
- rest-ehr-scape/src/main/java/org/ehrbase/rest/ehrscape/controller/BaseController.java
- rest-ehr-scape/src/main/java/org/ehrbase/rest/ehrscape/controller/CompositionController.java
- rest-ehr-scape/src/main/java/org/ehrbase/rest/ehrscape/controller/EhrController.java
- rest-ehr-scape/src/main/java/org/ehrbase/rest/ehrscape/controller/TemplateController.java
- rest-openehr/src/main/java/org/ehrbase/rest/BaseController.java
- rest-openehr/src/main/java/org/ehrbase/rest/openehr/OpenehrCompositionController.java
- rest-openehr/src/main/java/org/ehrbase/rest/openehr/OpenehrContributionController.java
- rest-openehr/src/main/java/org/ehrbase/rest/openehr/OpenehrDefinitionQueryController.java
- rest-openehr/src/main/java/org/ehrbase/rest/openehr/OpenehrDirectoryController.java
- rest-openehr/src/main/java/org/ehrbase/rest/openehr/OpenehrEhrController.java
- rest-openehr/src/main/java/org/ehrbase/rest/openehr/OpenehrEhrStatusController.java
- rest-openehr/src/main/java/org/ehrbase/rest/openehr/OpenehrQueryController.java
- rest-openehr/src/main/java/org/ehrbase/rest/openehr/OpenehrTemplateController.java
- rest-openehr/src/main/java/org/ehrbase/rest/openehr/OpenehrVersionedCompositionController.java
- rest-openehr/src/main/java/org/ehrbase/rest/openehr/OpenehrVersionedEhrStatusController.java
> add location

- CHANGELOG.md
- api/src/main/java/org/ehrbase/api/service/CompositionService.java
- rest-openehr/src/main/java/org/ehrbase/rest/openehr/audit/CompositionAuditInterceptor.java
- service/src/main/java/org/ehrbase/dao/access/interfaces/I_EntryAccess.java
- service/src/main/java/org/ehrbase/dao/access/jooq/EntryAccess.java
- service/src/main/java/org/ehrbase/service/CompositionServiceImp.java
> retrieve only template id

- CHANGELOG.md
- application/src/main/java/org/ehrbase/application/abac/CustomMethodSecurityExpressionRoot.java
> Handle empty response with http status  204

- rest-openehr/src/main/java/org/ehrbase/rest/openehr/audit/OpenEhrAuditDataset.java
> Fixed potential Nullpointer

- .github/workflows/codeql.yml
Added CodeQL GitHub action to scan for security issues.
> Add CodeQL GitHub action

- CHANGELOG.md
- base/src/main/resources/db/migration/V83__change_sys_tenant_to_short.sql
- base/src/main/resources/db/migration/beforeValidate.sql
> fix the script

- bom/pom.xml
> change to latest json-path

- api/src/main/java/org/ehrbase/api/audit/interceptor/AuditCompensationInterceptor.java
- api/src/main/java/org/ehrbase/api/audit/interceptor/AuditCompositionInterceptor.java
- api/src/main/java/org/ehrbase/api/audit/interceptor/AuditContributionInterceptor.java
- api/src/main/java/org/ehrbase/api/audit/interceptor/AuditEhrAdminInterceptor.java
- api/src/main/java/org/ehrbase/api/audit/interceptor/AuditEhrInterceptor.java
- api/src/main/java/org/ehrbase/api/audit/interceptor/AuditEhrStatusInterceptor.java
- api/src/main/java/org/ehrbase/api/audit/interceptor/AuditInterceptor.java
- api/src/main/java/org/ehrbase/api/audit/interceptor/AuditQueryInterceptor.java
- application/src/main/java/org/ehrbase/application/config/web/AuditHandlerInterceptorDelegator.java
- application/src/main/java/org/ehrbase/application/config/web/AuditInterceptorHandler.java
- rest-openehr/src/main/java/org/ehrbase/rest/BaseController.java
> refactoring & compensation

- api/src/main/java/org/ehrbase/api/audit/msg/AuditMsg.java
- api/src/main/java/org/ehrbase/api/audit/msg/AuditMsgBuilder.java
- application/src/main/java/org/ehrbase/application/config/web/AuditInterceptorHandler.java
- rest-openehr/src/main/java/org/ehrbase/rest/openehr/OpenehrDefinitionQueryController.java
- rest-openehr/src/main/java/org/ehrbase/rest/openehr/OpenehrQueryController.java
> fix query & add stored query endpoint

- api/src/main/java/org/ehrbase/api/audit/interceptor/AuditDirectoryInterceptor.java
- api/src/main/java/org/ehrbase/api/audit/msg/AuditMsg.java
- api/src/main/java/org/ehrbase/api/audit/msg/AuditMsgBuilder.java
- application/src/main/java/org/ehrbase/application/config/web/AuditInterceptorHandler.java
- rest-openehr/src/main/java/org/ehrbase/rest/admin/AdminDirectoryController.java
- rest-openehr/src/main/java/org/ehrbase/rest/openehr/OpenehrDirectoryController.java
> add audit directory

- .github/dependabot.yml
- .github/workflows/build-multiarch-image-latest.yml
- .github/workflows/build-multiarch-image-next.yml
- .github/workflows/build-multiarch-image-tag.yml
- .github/workflows/build.yml
- .github/workflows/codeql.yml
- .github/workflows/jdk-compat-robot.yml
- .github/workflows/jdk-compat.yml
Update GitHub actions to the latest versions to avoid deprecation warnings.
Added dependabot support for github-actions
https://statics.teams.cdn.office.net/evergreen-assets/safelinks/1/atp-safelinks.html
> Update GitHub actions to latest versions

- service/src/main/java/org/ehrbase/service/TemplateServiceImp.java
> fixed the response when invalid templated id 

- .circleci/config.yml
Enable STORED QUERY Robot test suite in Circle CI
> feat: cdr-1068 enable Robot STORED QUERY test suite in CIRCLE CI

- CHANGELOG.md
- service/src/main/java/org/ehrbase/repository/EhrFolderRepository.java
> fix the audit default status type

- service/src/main/java/org/ehrbase/service/CompositionServiceImp.java
> handle IllegalArgumentException

- rest-openehr/src/main/java/org/ehrbase/rest/openehr/OpenehrEhrController.java
- rest-openehr/src/main/java/org/ehrbase/rest/openehr/OpenehrEhrStatusController.java
> add url to ehr & ehr status

- .github/workflows/build-and-test-postgres.yml
Add action permission that allows dependabot triggered action to collect the jnuit reports.
> CDR-1378 Add github action permission for test reporter

- .github/workflows/build-and-test-postgres.yml
Skip any publishing for actions triggered by dependabot.
> [CDR-1378] Skip any publishing for actions triggered by dependabot

- .github/workflows/build_and_test.yml
- .github/workflows/codestyle.yml
Undo style check workflow merge-
> CDR-1381 Undo style check workflow merge

- .github/workflows/build_and_test.yml
- .github/workflows/check-codeql.yml
- .github/workflows/check-style.yml
> Inherit secrets for github action workflow_call

- CHANGELOG.md
- aql-engine/src/main/java/org/ehrbase/openehr/aqlengine/asl/model/field/AslDvOrderedColumnField.java
- aql-engine/src/test/java/org/ehrbase/openehr/aqlengine/sql/AqlSqlQueryBuilderTest.java
> CDR-1404 Fix AslDvOrderedColumnField::copyWithOwner

- .github/workflows/build_and_test.yml
- .github/workflows/check-codeql.yml
- .github/workflows/check-style.yml
Correct naming for github actions
> Fix invalid github action naming

- .github/workflows/build_and_test.yml
- .github/workflows/collect-junit-results.yml
Fix invalid job dependency of Junit artifact cleanup
> Fix invalid job dependency

- .github/workflows/collect-junit-results.yml
> Download JUnit artifact due to incompatibility of test-reporter with artifact@v4

- .github/workflows/collect-junit-results.yml
The JUnit artifacts needs to be downloaded from the workflow_run/workflow - Build & Test.
> Download artifact from workflow_run

- .github/workflows/build_and_test.yml
- .github/workflows/collect-junit-results.yml
- .github/workflows/release.yml
Change secret used for github token
> Change github token used for actions

- api/src/main/java/org/ehrbase/api/rest/EHRbaseHeader.java
> CDR-1430 change debugging header names

- .github/workflows/build_and_test.yml
Use extracted sonar report workflow_run.
> Use extracted sonar workflow_run

- .github/workflows/build_and_test.yml
- .github/workflows/report-robot-results.yml
- .github/workflows/report-sonar-results.yml
Use new robot PR workflow run to fix failing PR https://github.com/ehrbase/ehrbase/pull/1339.
> CDR-1487 Use workflow_run for robot PR reports

- api/src/main/java/org/ehrbase/api/service/CompositionService.java
- rest-ehr-scape/src/main/java/org/ehrbase/rest/ehrscape/controller/CompositionController.java
- service/src/main/java/org/ehrbase/service/CompositionServiceImp.java
Cleanup Composition Service
- removed obsolete method
- return optional for ehr_id for comp_id
- adjust method arguments for compositionIds
> CDR-1507 Cleanup Composition service

- .github/workflows/release.yml
Step use and run can't be used together
> [CDR-909] Step use and run can't be used together

- bom/pom.xml
> CDR-1512 Bump SDK version to 2.15.0-SNAPSHOT

- rest-ehr-scape/src/main/java/org/ehrbase/rest/ehrscape/controller/CompositionController.java
>  CDR-1530 Fix ehrscape comp get by return proper 404

- jooq-pg/src/main/resources/db/migration/ehr/V15__data_tables_add_parent_num.sql
- jooq-pg/src/main/resources/db/migration/ehr/V15__data_tables_add_parent_num.sql.conf
- jooq-pg/src/main/resources/db/migration/ehr/beforeValidate.sql
> CDR-1532 Update Postgres v15 migration

- CHANGELOG.md
- service/src/main/java/org/ehrbase/service/StoredQueryServiceImp.java
> CDR-1597 aql query storage: evict correct entries from cache

- api/pom.xml
- api/src/main/java/org/ehrbase/api/service/StoredQueryService.java
- application/pom.xml
- aql-engine/pom.xml
- bom/pom.xml
- cli/pom.xml
- configuration/pom.xml
- jooq-pg/pom.xml
- plugin/pom.xml
- pom.xml
- rest-ehr-scape/pom.xml
- rest-openehr/pom.xml
- rest-openehr/src/main/java/org/ehrbase/rest/openehr/OpenehrDefinitionQueryController.java
- rest-openehr/src/test/java/org/ehrbase/rest/openehr/OpenehrDefinitionQueryControllerTest.java
- rest-openehr/src/test/java/org/ehrbase/rest/openehr/OpenehrQueryControllerTest.java
- rm-db-format/pom.xml
- service/pom.xml
- service/src/main/java/org/ehrbase/service/StoredQueryServiceImp.java
- service/src/test/java/org/ehrbase/service/StoredQueryServiceTest.java
- test-coverage/pom.xml
> Fix HTTP 500 in case stored query does not exist

- .github/workflows/build_and_test.yml
- CHANGELOG.md
- UPDATING.md
- configuration/src/main/resources/application.yml
- rest-ehr-scape/src/main/java/org/ehrbase/rest/ehrscape/RestEHRScapeModuleConfiguration.java
- rest-openehr/src/main/java/org/ehrbase/rest/RestModuleConfiguration.java
- rest-openehr/src/main/java/org/ehrbase/rest/status/StatusController.java
> CDR-1609 Property for enabling ehrscape API (default: false)

- configuration/src/main/resources/application.yml
Disable AQL on Folder per default
> CDR-1580 Disable AQL on Folder per default

- bom/pom.xml
> Bump spring-boot.version from 3.2.10 to 3.2.11

- service/src/main/java/org/ehrbase/service/KnowledgeCacheServiceImp.java
Ensure SQLExceptions like connection issues are propagated correctly
> CDR-1658 Forward underlaying SQLException

- CHANGELOG.md
- aql-engine/src/main/java/org/ehrbase/openehr/aqlengine/service/AqlQueryServiceImp.java
- aql-engine/src/test/java/org/ehrbase/openehr/aqlengine/service/AqlQueryServiceImpTest.java
> CDR-1698 Remove redundant EHR from AQL queries

- aql-engine/src/main/java/org/ehrbase/openehr/aqlengine/asl/AqlSqlLayer.java
- aql-engine/src/main/java/org/ehrbase/openehr/aqlengine/asl/AslFromCreator.java
- aql-engine/src/main/java/org/ehrbase/openehr/aqlengine/asl/AslPathCreator.java
- aql-engine/src/main/java/org/ehrbase/openehr/aqlengine/asl/model/AslStructureColumn.java
- aql-engine/src/main/java/org/ehrbase/openehr/aqlengine/asl/model/condition/AslDvOrderedValueQueryCondition.java
- aql-engine/src/main/java/org/ehrbase/openehr/aqlengine/asl/model/field/AslRmPathField.java
- aql-engine/src/main/java/org/ehrbase/openehr/aqlengine/asl/model/field/AslVirtualField.java
- aql-engine/src/main/java/org/ehrbase/openehr/aqlengine/asl/model/query/AslFilteringQuery.java
- aql-engine/src/main/java/org/ehrbase/openehr/aqlengine/asl/model/query/AslRootQuery.java
- aql-engine/src/main/java/org/ehrbase/openehr/aqlengine/asl/model/query/AslStructureQuery.java
- aql-engine/src/main/java/org/ehrbase/openehr/aqlengine/querywrapper/AqlQueryWrapper.java
- aql-engine/src/main/java/org/ehrbase/openehr/aqlengine/sql/AqlSqlQueryBuilder.java
- aql-engine/src/main/java/org/ehrbase/openehr/aqlengine/sql/ConditionUtils.java
- aql-engine/src/main/java/org/ehrbase/openehr/aqlengine/sql/EncapsulatingQueryUtils.java
- aql-engine/src/main/java/org/ehrbase/openehr/aqlengine/sql/FieldUtils.java
- aql-engine/src/test/java/org/ehrbase/openehr/aqlengine/asl/AqlSqlLayerTest.java
- aql-engine/src/test/java/org/ehrbase/openehr/aqlengine/asl/AslGraph.java
- aql-engine/src/test/java/org/ehrbase/openehr/aqlengine/sql/AqlSqlQueryBuilderTest.java
- jooq-pg/src/main/java/org/ehrbase/jooq/pg/util/AdditionalSQLFunctions.java
> Feature/CDR-1434 - AQL Optimizations

- CHANGELOG.md
- aql-engine/src/main/java/org/ehrbase/openehr/aqlengine/asl/AslFromCreator.java
- aql-engine/src/test/java/org/ehrbase/openehr/aqlengine/sql/AqlSqlQueryBuilderTest.java
> CDR-1760 Handle "FOLDER CONTAINS VERSION CONTAINS COMPOSITION" correctly

- UPDATING.md
- bom/pom.xml
> CDR-1766 Update to SDK 2.21.0

- aql-engine/src/main/java/org/ehrbase/openehr/aqlengine/sql/AqlSqlQueryBuilder.java
- rm-db-format/src/main/java/org/ehrbase/openehr/dbformat/DbToRmFormat.java
> CDR-1810 Omit shortening paths for RM_OBJECT aggregates

- configuration/src/main/java/org/ehrbase/configuration/config/SwaggerConfiguration.java
- rest-openehr/src/main/java/org/ehrbase/rest/openehr/specification/QueryApiSpecification.java
Cleanup openapi documentation.
> Cleanup documentation

- CHANGELOG.md
- api/pom.xml
- cli/src/main/java/org/ehrbase/cli/CliRunner.java
Add missing test dependency scope to assertj
> Add missing test dependency scope to assertj

- service/src/main/java/org/ehrbase/service/PersistenceConfig.java
> apply tx-manager customizers to custom tx manager

- aql-engine/src/main/java/org/ehrbase/openehr/aqlengine/sql/AqlSqlQueryBuilder.java
- aql-engine/src/main/java/org/ehrbase/openehr/aqlengine/sql/EncapsulatingQueryUtils.java
- aql-engine/src/main/java/org/ehrbase/openehr/aqlengine/sql/postprocessor/DefaultResultPostprocessor.java
- rm-db-format/src/main/java/org/ehrbase/openehr/dbformat/DbToRmFormat.java
- rm-db-format/src/test/java/org/ehrbase/openehr/dbformat/DbToRmFormatTest.java
- service/src/main/java/org/ehrbase/repository/AbstractVersionedObjectRepository.java
- service/src/main/java/org/ehrbase/repository/CompositionRepository.java
- service/src/main/java/org/ehrbase/repository/EhrFolderRepository.java
> CDR-2015 load RM-Objects concatenated as array

- CHANGELOG.md
- aql-engine/src/main/java/org/ehrbase/openehr/aqlengine/asl/AslUtils.java
- aql-engine/src/main/java/org/ehrbase/openehr/aqlengine/sql/ConditionUtils.java
- aql-engine/src/test/java/org/ehrbase/openehr/aqlengine/asl/AslUtilsTest.java
- aql-engine/src/test/java/org/ehrbase/openehr/aqlengine/sql/ConditionUtilsTest.java
- rm-db-format/src/main/java/org/ehrbase/openehr/dbformat/DbToRmFormat.java
> CDR-1675 fixed aql like escaping
